// ==========================================================================
// DIGI MASTER — runtime-panel media engine (generated by Moonahs Mod Maker).
// CONFIG and LIBRARY below are injected at compile time from the app's
// Jumpscares/Deaths tab; the engine itself is static. Panels are created on
// demand with $.CreatePanel and deleted after playback, so videos cost zero
// decode while nothing is showing and always start from frame 0.
// Diagnostics: watch the console for [DigiV2].
// ==========================================================================

var CONFIG = /*__DIGI_CONFIG__*/{}/*__END__*/;
var LIBRARY = /*__DIGI_LIBRARY__*/{ SCARES: [], DEATHS: [] }/*__END__*/;

var _timerHandle = null;
var _deathPollHandle = null;
var _isRespawning = false;
var _deathCooldownTs = 0;
var _liveN = 0;

// ==========================================================================
// MEDIA ENGINE — create, show, destroy.
// ==========================================================================
function spawnPanel(entry) {
    var container = $("#MediaOverlayContainer");
    if (!container) {
        $.Msg("[DigiV2] ERROR: MediaOverlayContainer missing from base_hud.xml");
        return null;
    }
    var id = "DigiLive_" + (_liveN++);
    var panel = null;

    if (entry.type === "video") {
        try {
            panel = $.CreatePanel("MoviePanel", container, id, {
                src: entry.src,
                repeat: "true",
                autoplay: "onload",
                controls: "none",
                disableactivatepause: "true",
                volume: "0",
                hittest: "false",
            });
        } catch (e) {
            $.Msg("[DigiV2] CreatePanel(MoviePanel, props) threw: " + e);
        }
        if (panel) {
            if (panel.SetMovie) { try { panel.SetMovie(entry.src); } catch (e) {} }
            if (panel.SetRepeat) { try { panel.SetRepeat(true); } catch (e) {} }
            if (panel.SetPlaybackVolume) { try { panel.SetPlaybackVolume(0); } catch (e) {} }
            if (panel.Play) { try { panel.Play(); } catch (e) {} }
        }
    } else {
        try {
            panel = $.CreatePanel("Image", container, id, { hittest: "false" });
        } catch (e) {
            $.Msg("[DigiV2] CreatePanel(Image) threw: " + e);
        }
        if (panel && panel.SetImage) panel.SetImage(entry.src);
    }

    if (!panel) {
        $.Msg("[DigiV2] ERROR: CreatePanel unsupported — report this");
        return null;
    }
    panel.AddClass("digi-media");
    panel.AddClass("digi-" + (entry.preset || "fullscreen"));
    return panel;
}

function TriggerMedia(entry) {
    if (!entry) return;
    $.Msg("[DigiV2] trigger: " + entry.name);
    if (entry.sound) $.DispatchEvent("PlaySoundEffect", entry.sound);

    var panel = spawnPanel(entry);
    if (!panel) return;

    $.Schedule(0.05, function () {
        if (panel && panel.IsValid && panel.IsValid()) panel.AddClass("digi-show");
    });
    $.Schedule(entry.show + 0.05, function () {
        if (panel && panel.IsValid && panel.IsValid()) panel.RemoveClass("digi-show");
    });
    $.Schedule(entry.show + 2.4, function () {
        if (panel && panel.IsValid && panel.IsValid()) panel.DeleteAsync(0.0);
    });
}

// ==========================================================================
// RNG LOOP (jumpscares)
// ==========================================================================
function RunRngLoop() {
    if (!CONFIG.IS_ENABLED || LIBRARY.SCARES.length === 0) {
        _timerHandle = $.Schedule(2.0, RunRngLoop);
        return;
    }
    if (Math.random() * 100 < CONFIG.SCARE_CHANCE) {
        TriggerMedia(LIBRARY.SCARES[Math.floor(Math.random() * LIBRARY.SCARES.length)]);
    }
    _timerHandle = $.Schedule(CONFIG.RNG_INTERVAL, RunRngLoop);
}

// ==========================================================================
// DEATH POLLER — 4Hz, cached respawn-timer label.
// ==========================================================================
var _cachedTimerLabel = null;

function findRespawnLabel() {
    if (_cachedTimerLabel && _cachedTimerLabel.IsValid && _cachedTimerLabel.IsValid()) {
        return _cachedTimerLabel;
    }
    _cachedTimerLabel = null;
    var ctx = $.GetContextPanel();
    var root = ctx.GetParent() || ctx;
    var labels = root.FindChildrenWithClassTraverse("respawn_number");
    for (var i = 0; i < labels.length; i++) {
        if (labels[i]) {
            _cachedTimerLabel = labels[i];
            break;
        }
    }
    return _cachedTimerLabel;
}

function RunDeathPoller() {
    var label = findRespawnLabel();
    var timerValue = 0;
    if (label && label.text) {
        var v = parseInt(label.text);
        if (!isNaN(v)) timerValue = v;
    }

    if (timerValue > 2) {
        if (!_isRespawning) {
            _isRespawning = true;
            if (CONFIG.IS_ENABLED && LIBRARY.DEATHS.length > 0 && Date.now() > _deathCooldownTs) {
                if (Math.random() * 100 < CONFIG.DEATH_CHANCE) {
                    $.Msg("[DigiV2] death detected (" + timerValue + "s respawn)");
                    TriggerMedia(LIBRARY.DEATHS[Math.floor(Math.random() * LIBRARY.DEATHS.length)]);
                }
                _deathCooldownTs = Date.now() + (timerValue + 5) * 1000;
            }
        }
    } else {
        _isRespawning = false;
    }
    _deathPollHandle = $.Schedule(0.25, RunDeathPoller);
}

// ==========================================================================
// INIT
// ==========================================================================
(function () {
    if (_timerHandle) $.CancelScheduled(_timerHandle);
    if (_deathPollHandle) $.CancelScheduled(_deathPollHandle);
    $.Msg("[DigiV2] engine loaded — " + LIBRARY.SCARES.length + " scares, " + LIBRARY.DEATHS.length + " deaths");
    _timerHandle = $.Schedule(5.0, RunRngLoop);
    _deathPollHandle = $.Schedule(5.0, RunDeathPoller);
})();

// ==========================================================================
// ANITA-UI INTEGRATION
// ==========================================================================
function anitaCallback(id, value) {
    if (id === "TEST_SCARE" && LIBRARY.SCARES.length > 0) {
        TriggerMedia(LIBRARY.SCARES[Math.floor(Math.random() * LIBRARY.SCARES.length)]);
        return;
    }
    if (id === "TEST_DEATH" && LIBRARY.DEATHS.length > 0) {
        TriggerMedia(LIBRARY.DEATHS[Math.floor(Math.random() * LIBRARY.DEATHS.length)]);
        return;
    }
    if (typeof id === "string" && id.indexOf("TEST_LIB_") === 0) {
        var parts = id.split("_");
        var list = LIBRARY[parts[2]];
        var idx = parseInt(parts[3]);
        if (list && list[idx]) TriggerMedia(list[idx]);
        return;
    }
    if (CONFIG.hasOwnProperty(id)) CONFIG[id] = value;
    if (id === "RNG_INTERVAL" || id === "SCARE_CHANCE") {
        if (_timerHandle) $.CancelScheduled(_timerHandle);
        RunRngLoop();
    }
}

(function () {
    var menuConfig = {
        title: "DigiMaster (Mod Maker)",
        description: "Jumpscare & Death Manager — configured in Moonahs Mod Maker",
        elements: [
            { type: "toggle", label: "Enable Mod", id: "IS_ENABLED", defaultValue: CONFIG.IS_ENABLED },
            { type: "stepper", label: "RNG Interval", id: "RNG_INTERVAL", min: 5, max: 120, step: 1, defaultValue: CONFIG.RNG_INTERVAL },
            { type: "stepper", label: "Scare Chance %", id: "SCARE_CHANCE", min: 1, max: 100, step: 1, defaultValue: CONFIG.SCARE_CHANCE },
            { type: "stepper", label: "Death Chance %", id: "DEATH_CHANCE", min: 0, max: 100, step: 1, defaultValue: CONFIG.DEATH_CHANCE },
            { type: "button", label: "Test Random Scare", id: "TEST_SCARE" },
            { type: "button", label: "Test Random Death", id: "TEST_DEATH" },
        ],
    };
    var i;
    for (i = 0; i < LIBRARY.SCARES.length; i++) {
        menuConfig.elements.push({ type: "button", label: "Test: " + LIBRARY.SCARES[i].name, id: "TEST_LIB_SCARES_" + i });
    }
    for (i = 0; i < LIBRARY.DEATHS.length; i++) {
        menuConfig.elements.push({ type: "button", label: "Test: " + LIBRARY.DEATHS[i].name, id: "TEST_LIB_DEATHS_" + i });
    }

    $.RegisterForUnhandledEvent("ClientUI_FireOutput", function (payload) {
        try {
            var data = typeof payload === "string" ? JSON.parse(payload) : payload;
            if (data.magic_word === "ANITA_ALIVE") { _anitaConnect.done = false; _anitaConnect(); }
            if (data.magic_word === "ANITA_HANDSHAKE" && data.mod_title === menuConfig.title) { _anitaConnect.done = true; }
            if (data.magic_word === "ANITA_UPDATE" && data.mod_title === menuConfig.title) {
                if (data.setting_id) {
                    var val = data.value;
                    if (CONFIG.hasOwnProperty(data.setting_id) && typeof CONFIG[data.setting_id] === "number" && typeof val === "boolean") {
                        val = val ? 1 : 0;
                    }
                    anitaCallback(data.setting_id, val);
                }
            }
        } catch (e) {}
    });
    function _anitaConnect() {
        if (_anitaConnect.done) return;
        $.DispatchEvent("ClientUI_FireOutput", JSON.stringify({ magic_word: "ANITA_REGISTER", config: menuConfig }));
        $.Schedule(1.0, _anitaConnect);
    }
    _anitaConnect();
})();
