import { useEffect, useMemo, useRef, useState } from "react";
import { convertFileSrc } from "@tauri-apps/api/core";
import { open as openDialog } from "@tauri-apps/plugin-dialog";
import { posterSheet } from "../lib/api";
import { useToast } from "./Toaster";
import type { PosterOverride } from "../types";
import manifestJson from "../data/posterManifest.json";

// The atlas rect manifest is generated by tools/poster-manifest (see its
// README): every in-world poster/sign/graffiti is a pixel rect of a
// materials/overlays sheet; the map's baked UVs pick the rect, so replacing
// the pixels replaces every surface that shows it.
interface ManifestPoster {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  alphaCoverage?: number;
}
interface ManifestSheet {
  id: string;
  category: string;
  curated: boolean;
  materials: string[];
  colorTexture: string;
  transTexture: string | null;
  width: number;
  height: number;
  posters: ManifestPoster[];
}

const SHEETS = (manifestJson as { sheets: ManifestSheet[] }).sheets;

const CATEGORIES: { key: string; label: string; hint: string }[] = [
  { key: "posters", label: "Posters", hint: "Street posters, newspapers, stickers" },
  { key: "signage", label: "Signs & Billboards", hint: "Shop signs, street & subway signage" },
  { key: "ghostsigns", label: "Ghost Signs", hint: "Faded painted wall ads" },
  { key: "graffiti", label: "Graffiti", hint: "Tags and murals" },
  { key: "sigils", label: "Sigils", hint: "Occult wall markings" },
];

const IMAGE_FILTERS = [{ name: "Image", extensions: ["png", "jpg", "jpeg", "webp", "bmp"] }];

function pretty(id: string): string {
  return id
    .replace(/^(labels_posters_|posters_|poster_|overlay_|signage_|signs_|graffiti_|item_)/, "")
    .replace(/[/_]+/g, " ")
    .trim();
}

export function PostersTab({
  helperPath,
  pakPath,
  overrides,
  accent,
  onAdd,
  onUpdate,
  onRemove,
  registerDropHandler,
}: {
  helperPath: string;
  pakPath: string;
  overrides: PosterOverride[];
  accent: string;
  onAdd: (ov: PosterOverride) => void;
  onUpdate: (id: string, patch: Partial<PosterOverride>) => void;
  onRemove: (id: string) => void;
  /** Lets the app-level OS drag-drop route dropped images to the rect under
   *  the cursor. Pass null on unmount. Returns true when a rect took the drop. */
  registerDropHandler: (fn: ((paths: string[], cssX: number, cssY: number) => boolean) | null) => void;
}) {
  const { push } = useToast();
  const [category, setCategory] = useState<string | null>(null);
  const [sheet, setSheet] = useState<ManifestSheet | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [sheetImg, setSheetImg] = useState<{ src: string; forSheet: string } | null>(null);
  const [sheetErr, setSheetErr] = useState<string | null>(null);
  const sheetRef = useRef<ManifestSheet | null>(null);
  sheetRef.current = sheet;

  const byId = useMemo(() => new Map(overrides.map((o) => [o.id, o])), [overrides]);

  // Load (decompile once + cache) the sheet's color texture for display.
  useEffect(() => {
    if (!sheet) return;
    let cancelled = false;
    setSheetErr(null);
    setSheetImg(null);
    posterSheet(helperPath, pakPath, sheet.materials[0])
      .then((s) => !cancelled && setSheetImg({ src: convertFileSrc(s.colorPng), forSheet: sheet.id }))
      .catch((e) => !cancelled && setSheetErr(String(e)));
    return () => {
      cancelled = true;
    };
  }, [sheet, helperPath, pakPath]);

  function assign(sh: ManifestSheet, poster: ManifestPoster, imagePath: string) {
    const id = `${sh.id}::${poster.id}`;
    const existing = byId.get(id);
    if (existing) {
      onUpdate(id, { sourceImage: imagePath });
    } else {
      onAdd({
        id,
        sheetId: sh.id,
        materials: sh.materials,
        posterId: poster.id,
        label: `${pretty(sh.id)} · ${pretty(poster.id)}`,
        x: poster.x,
        y: poster.y,
        w: poster.w,
        h: poster.h,
        alphaCoverage: poster.alphaCoverage ?? 1,
        sourceImage: imagePath,
        fit: "cover",
        lastCompiledHash: null,
      });
    }
    setSelected(id);
    push("success", `Poster art set — ${pretty(poster.id)} (${poster.w}×${poster.h})`);
  }

  async function pickImage(sh: ManifestSheet, poster: ManifestPoster) {
    const picked = await openDialog({ multiple: false, filters: IMAGE_FILTERS });
    if (typeof picked === "string") assign(sh, poster, picked);
  }

  // OS-level drops: the app forwards dropped image paths + cursor position.
  useEffect(() => {
    registerDropHandler((paths, cssX, cssY) => {
      const sh = sheetRef.current;
      if (!sh || paths.length === 0) return false;
      const el = document.elementFromPoint(cssX, cssY)?.closest("[data-poster-rect]");
      const pid = el?.getAttribute("data-poster-rect");
      const poster = sh.posters.find((p) => p.id === pid);
      if (!poster) return false;
      assign(sh, poster, paths[0]);
      return true;
    });
    return () => registerDropHandler(null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [overrides]);

  // ---- Category grid --------------------------------------------------------
  if (!category) {
    return (
      <div>
        <p className="mb-4 text-sm text-zinc-500">
          Replace any in-world poster, sign, or graffiti with your own image — drop a PNG on a
          highlighted region (or click it) and the compile paints it into the game's texture
          atlas.
          {overrides.length > 0 && (
            <span className="ml-1 text-emerald-400">
              {overrides.length} poster{overrides.length === 1 ? "" : "s"} queued.
            </span>
          )}
        </p>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
          {CATEGORIES.map((c) => {
            const sheets = SHEETS.filter((s) => s.category === c.key);
            if (sheets.length === 0) return null;
            const n = overrides.filter((o) => sheets.some((s) => s.id === o.sheetId)).length;
            const regions = sheets.reduce((acc, s) => acc + s.posters.length, 0);
            return (
              <button
                key={c.key}
                onClick={() => setCategory(c.key)}
                className="group relative flex flex-col rounded-xl border border-zinc-800 bg-zinc-900/40 p-4 text-left transition hover:border-zinc-600 hover:bg-zinc-900"
              >
                <span className="text-sm font-semibold text-zinc-100">{c.label}</span>
                <span className="mt-1 text-[11px] text-zinc-500">{c.hint}</span>
                <span className="mt-2 text-[10px] text-zinc-600">
                  {sheets.length} sheets · {regions} regions
                </span>
                {n > 0 && (
                  <span className="absolute right-2 top-2 rounded bg-emerald-500/15 px-1.5 text-[10px] font-semibold text-emerald-300">
                    {n}
                  </span>
                )}
              </button>
            );
          })}
        </div>
        {overrides.length > 0 && (
          <div className="mt-6">
            <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-zinc-500">
              Your poster mods
            </h3>
            <div className="flex flex-col gap-1">
              {overrides.map((o) => (
                <div
                  key={o.id}
                  className="flex items-center gap-3 rounded-lg border border-zinc-800 bg-zinc-900/40 px-3 py-1.5"
                >
                  <img
                    src={convertFileSrc(o.sourceImage)}
                    className="h-8 w-8 rounded object-cover"
                    alt=""
                  />
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-xs text-zinc-200">{o.label}</div>
                    <div className="truncate text-[10px] text-zinc-500">
                      {o.w}×{o.h} · {o.fit}
                    </div>
                  </div>
                  <button
                    onClick={() => {
                      const sh = SHEETS.find((s) => s.id === o.sheetId);
                      if (sh) {
                        setCategory(sh.category);
                        setSheet(sh);
                        setSelected(o.id);
                      }
                    }}
                    className="rounded px-2 py-0.5 text-[11px] text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200"
                  >
                    View
                  </button>
                  <button
                    onClick={() => onRemove(o.id)}
                    className="rounded px-2 py-0.5 text-[11px] text-red-400/80 hover:bg-red-500/10 hover:text-red-300"
                  >
                    Remove
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    );
  }

  // ---- Sheet grid within a category ----------------------------------------
  if (!sheet) {
    const sheets = SHEETS.filter((s) => s.category === category);
    return (
      <div>
        <button
          onClick={() => setCategory(null)}
          className="mb-3 text-xs text-zinc-500 hover:text-zinc-300"
        >
          ← All categories
        </button>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
          {sheets.map((s) => {
            const n = overrides.filter((o) => o.sheetId === s.id).length;
            return (
              <button
                key={s.id}
                onClick={() => {
                  setSheet(s);
                  setSelected(null);
                }}
                className="group relative flex flex-col rounded-xl border border-zinc-800 bg-zinc-900/40 p-4 text-left transition hover:border-zinc-600 hover:bg-zinc-900"
              >
                <span className="truncate text-sm font-semibold text-zinc-100">{pretty(s.id)}</span>
                <span className="mt-1 text-[11px] text-zinc-500">
                  {s.posters.length} region{s.posters.length === 1 ? "" : "s"} · {s.width}×
                  {s.height}
                  {!s.curated && " · auto-mapped"}
                </span>
                {n > 0 && (
                  <span className="absolute right-2 top-2 rounded bg-emerald-500/15 px-1.5 text-[10px] font-semibold text-emerald-300">
                    {n}
                  </span>
                )}
              </button>
            );
          })}
        </div>
      </div>
    );
  }

  // ---- Sheet detail: image + clickable rect overlays ------------------------
  const selectedOv = selected ? byId.get(selected) : undefined;
  const selectedDef = selected
    ? sheet.posters.find((p) => `${sheet.id}::${p.id}` === selected)
    : undefined;
  return (
    <div>
      <div className="mb-3 flex items-center gap-2">
        <button
          onClick={() => {
            setSheet(null);
            setSelected(null);
          }}
          className="text-xs text-zinc-500 hover:text-zinc-300"
        >
          ← {CATEGORIES.find((c) => c.key === category)?.label ?? category}
        </button>
        <span className="text-xs text-zinc-600">/</span>
        <span className="text-xs font-semibold text-zinc-200">{pretty(sheet.id)}</span>
        <span className="text-[10px] text-zinc-600">
          {sheet.width}×{sheet.height}
          {!sheet.curated && " · auto-mapped regions"}
        </span>
      </div>
      <p className="mb-3 text-xs text-zinc-500">
        Drop an image onto a region (or click one) to replace that poster in-game.
      </p>
      {sheetErr && (
        <div className="mb-3 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-300">
          Couldn't load the sheet texture: {sheetErr}
        </div>
      )}
      <div className="flex flex-col gap-4 xl:flex-row">
        <div
          className="relative w-full max-w-3xl shrink-0 overflow-hidden rounded-lg border border-zinc-800 bg-zinc-950"
          style={{ aspectRatio: `${sheet.width} / ${sheet.height}` }}
        >
          {sheetImg?.forSheet === sheet.id ? (
            <img src={sheetImg.src} className="absolute inset-0 h-full w-full" alt="" />
          ) : (
            !sheetErr && (
              <div className="absolute inset-0 flex items-center justify-center text-xs text-zinc-600">
                Decoding sheet texture…
              </div>
            )
          )}
          {sheet.posters.map((p) => {
            const id = `${sheet.id}::${p.id}`;
            const ov = byId.get(id);
            const isSel = selected === id;
            return (
              <button
                key={p.id}
                data-poster-rect={p.id}
                title={`${pretty(p.id)} — ${p.w}×${p.h}`}
                onClick={() => {
                  setSelected(id);
                  if (!ov) void pickImage(sheet, p);
                }}
                className="absolute overflow-hidden transition"
                style={{
                  left: `${(p.x / sheet.width) * 100}%`,
                  top: `${(p.y / sheet.height) * 100}%`,
                  width: `${(p.w / sheet.width) * 100}%`,
                  height: `${(p.h / sheet.height) * 100}%`,
                  border: ov
                    ? "2px solid #34d399"
                    : isSel
                      ? `2px solid ${accent}`
                      : "1px solid rgba(255,255,255,0.25)",
                  boxShadow: isSel ? `0 0 0 2px ${accent}55` : undefined,
                  background: ov ? "transparent" : "rgba(0,0,0,0.0)",
                }}
              >
                {ov && (
                  <img
                    src={convertFileSrc(ov.sourceImage)}
                    className="h-full w-full"
                    style={{
                      objectFit:
                        ov.fit === "stretch" ? "fill" : (ov.fit as "cover" | "contain"),
                    }}
                    alt=""
                  />
                )}
              </button>
            );
          })}
        </div>
        <div className="min-w-0 flex-1">
          {selectedDef ? (
            <div className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-4">
              <div className="mb-1 text-sm font-semibold text-zinc-100">
                {pretty(selectedDef.id)}
              </div>
              <div className="mb-3 text-[11px] text-zinc-500">
                {selectedDef.w}×{selectedDef.h} at ({selectedDef.x},{selectedDef.y})
                {(selectedDef.alphaCoverage ?? 1) < 0.98 && (
                  <span className="ml-1 text-amber-400">
                    · shape-cut in vanilla — your art will fill the full rectangle
                  </span>
                )}
              </div>
              {selectedOv ? (
                <>
                  <img
                    src={convertFileSrc(selectedOv.sourceImage)}
                    className="mb-3 max-h-40 rounded-lg border border-zinc-800 object-contain"
                    alt=""
                  />
                  <div className="mb-3 flex items-center gap-2">
                    <span className="text-[11px] text-zinc-500">Fill mode</span>
                    {(["cover", "contain", "stretch"] as const).map((f) => (
                      <button
                        key={f}
                        onClick={() => onUpdate(selectedOv.id, { fit: f })}
                        className={`rounded px-2 py-0.5 text-[11px] ${
                          selectedOv.fit === f
                            ? "bg-zinc-100 font-semibold text-zinc-900"
                            : "bg-zinc-800 text-zinc-400 hover:text-zinc-200"
                        }`}
                      >
                        {f}
                      </button>
                    ))}
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => void pickImage(sheet, selectedDef)}
                      className="rounded-lg bg-zinc-800 px-3 py-1.5 text-xs text-zinc-200 hover:bg-zinc-700"
                    >
                      Replace image…
                    </button>
                    <button
                      onClick={() => onRemove(selectedOv.id)}
                      className="rounded-lg px-3 py-1.5 text-xs text-red-400/80 hover:bg-red-500/10 hover:text-red-300"
                    >
                      Remove
                    </button>
                  </div>
                </>
              ) : (
                <button
                  onClick={() => void pickImage(sheet, selectedDef)}
                  className="rounded-lg px-3 py-1.5 text-xs font-semibold text-zinc-900"
                  style={{ background: accent }}
                >
                  Choose image…
                </button>
              )}
            </div>
          ) : (
            <div className="rounded-xl border border-dashed border-zinc-800 p-4 text-xs text-zinc-600">
              Click a region on the sheet to replace it. Regions outlined green already have
              your art.
            </div>
          )}
          {overrides.filter((o) => o.sheetId === sheet.id).length > 0 && (
            <div className="mt-3 text-[11px] text-zinc-500">
              {overrides.filter((o) => o.sheetId === sheet.id).length} replacement
              {overrides.filter((o) => o.sheetId === sheet.id).length === 1 ? "" : "s"} on this
              sheet — all compile together.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
