import { useEffect, useMemo, useRef, useState } from "react";
import { convertFileSrc } from "@tauri-apps/api/core";
import { open as openDialog } from "@tauri-apps/plugin-dialog";
import { copyToDownloads, posterSheet } from "../lib/api";
import { useToast } from "./Toaster";
import type { PosterOverride } from "../types";
import manifestJson from "../data/posterManifest.json";

// The atlas rect manifest is generated by tools/poster-manifest (see its
// README): every in-world poster/sign/graffiti is a pixel rect of a
// materials/overlays sheet; the map's baked UVs pick the rect, so replacing
// the pixels replaces every surface that shows it. User corrections to the
// generated rects (drag-edited in edit mode) live in settings.posterRectEdits
// and are applied on top everywhere.
interface ManifestPoster {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  alphaCoverage?: number;
}
interface ManifestSheet {
  id: string;
  category: string;
  curated: boolean;
  materials: string[];
  colorTexture: string;
  transTexture: string | null;
  width: number;
  height: number;
  posters: ManifestPoster[];
}

export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

const SHEETS = (manifestJson as { sheets: ManifestSheet[] }).sheets;

const CATEGORIES: { key: string; label: string; hint: string; icon: string }[] = [
  { key: "posters", label: "Posters", hint: "Street posters, newspapers, stickers", icon: "▦" },
  { key: "signage", label: "Signs & Billboards", hint: "Shop signs, street & subway signage", icon: "◫" },
  { key: "ghostsigns", label: "Ghost Signs", hint: "Faded painted wall ads", icon: "▤" },
  { key: "graffiti", label: "Graffiti", hint: "Tags and murals", icon: "✎" },
  { key: "sigils", label: "Sigils", hint: "Occult wall markings", icon: "✦" },
];

const IMAGE_FILTERS = [{ name: "Image", extensions: ["png", "jpg", "jpeg", "webp", "bmp"] }];

/** Checkerboard = "this part is transparent in-game" (the usual convention),
 *  so shaped decals read as working instead of showing a black box. */
const CHECKER: React.CSSProperties = {
  backgroundImage:
    "conic-gradient(#3f3f46 90deg, #27272a 90deg 180deg, #3f3f46 180deg 270deg, #27272a 270deg)",
  backgroundSize: "12px 12px",
};

/** Pseudo region id for full-sheet replacements ("modify the original" flow). */
const WHOLE = "whole_sheet";

type DragMode = "move" | "n" | "s" | "e" | "w" | "nw" | "ne" | "sw" | "se";

/** In-rect preview of override art, honoring fit + rotation. For 90°/270° the
 *  element's dimensions swap (as fractions of the parent rect) so cover/
 *  contain fit the rotated footprint like the compile does. */
function artStyle(
  ov: { fit: string; rotation?: number },
  r: { w: number; h: number },
): React.CSSProperties {
  const rot = (ov.rotation ?? 0) % 360;
  const fitCss = (ov.fit === "stretch" ? "fill" : ov.fit) as React.CSSProperties["objectFit"];
  if (rot === 90 || rot === 270) {
    return {
      position: "absolute",
      left: "50%",
      top: "50%",
      width: `${(r.h / r.w) * 100}%`,
      height: `${(r.w / r.h) * 100}%`,
      transform: `translate(-50%, -50%) rotate(${rot}deg)`,
      objectFit: fitCss,
    };
  }
  return {
    // relative so the art paints above the shape-cut backdrop layer
    position: "relative",
    width: "100%",
    height: "100%",
    objectFit: fitCss,
    transform: rot ? `rotate(${rot}deg)` : undefined,
  };
}

function pretty(id: string): string {
  return id
    .replace(/^(labels_posters_|posters_|poster_|overlay_|signage_|signs_|graffiti_|item_)/, "")
    .replace(/[/_]+/g, " ")
    .trim();
}

// ---- Sheet thumbnail decoding -----------------------------------------------
// Decoding a sheet spawns the vpk helper (~1s each), so thumbnails decode
// through a sequential queue and cache for the session; the backend caches the
// PNG on disk so later sessions are instant.
const thumbCache = new Map<string, string>();
let thumbChain: Promise<void> = Promise.resolve();

function queueSheetPng(
  helperPath: string,
  pakPath: string,
  sheet: ManifestSheet,
  cb: (pngPath: string) => void,
): void {
  const cached = thumbCache.get(sheet.id);
  if (cached) return cb(cached);
  thumbChain = thumbChain.then(async () => {
    const hit = thumbCache.get(sheet.id);
    if (hit) return cb(hit);
    try {
      const s = await posterSheet(helperPath, pakPath, sheet.materials[0]);
      thumbCache.set(sheet.id, s.colorPng);
      cb(s.colorPng);
    } catch {
      /* thumbnail decode is best-effort */
    }
  });
}

function SheetThumb({
  helperPath,
  pakPath,
  sheet,
  dimmed,
}: {
  helperPath: string;
  pakPath: string;
  sheet: ManifestSheet;
  dimmed?: boolean;
}) {
  const [src, setSrc] = useState<string | null>(() => {
    const c = thumbCache.get(sheet.id);
    return c ? convertFileSrc(c) : null;
  });
  useEffect(() => {
    let cancelled = false;
    if (!src) {
      queueSheetPng(helperPath, pakPath, sheet, (p) => {
        if (!cancelled) setSrc(convertFileSrc(p));
      });
    }
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sheet.id]);
  return (
    <div
      className="relative w-full overflow-hidden rounded-lg bg-zinc-950"
      style={{ aspectRatio: "1 / 1", opacity: dimmed ? 0.5 : 1 }}
    >
      {src ? (
        <img
          src={src}
          loading="lazy"
          className="absolute inset-0 h-full w-full object-contain"
          alt=""
          draggable={false}
        />
      ) : (
        <div className="absolute inset-0 animate-pulse bg-zinc-900" />
      )}
    </div>
  );
}

export function PostersTab({
  helperPath,
  pakPath,
  overrides,
  accent,
  rectEdits,
  hidden,
  hiddenSheets,
  showUnused,
  customRegions,
  onCustomChange,
  onAdd,
  onUpdate,
  onRemove,
  onRectEdit,
  onToggleHidden,
  onToggleSheetHidden,
  registerDropHandler,
}: {
  helperPath: string;
  pakPath: string;
  overrides: PosterOverride[];
  accent: string;
  /** User rect corrections keyed `sheetId::posterId` (settings-persisted). */
  rectEdits: Record<string, Rect>;
  /** Region ids marked "unused" — invisible unless showUnused. */
  hidden: string[];
  /** Whole sheet ids marked "unused" — invisible unless showUnused. */
  hiddenSheets: string[];
  /** Settings → Experimental → "Show unused poster assets". */
  showUnused: boolean;
  /** User-drawn extra regions per sheet id (settings-persisted). */
  customRegions: Record<string, { id: string; x: number; y: number; w: number; h: number }[]>;
  onCustomChange: (
    sheetId: string,
    regions: { id: string; x: number; y: number; w: number; h: number }[],
  ) => void;
  onAdd: (ov: PosterOverride) => void;
  onUpdate: (id: string, patch: Partial<PosterOverride>) => void;
  onRemove: (id: string) => void;
  /** rect=null resets the region to its manifest rect. */
  onRectEdit: (id: string, rect: Rect | null) => void;
  onToggleHidden: (id: string) => void;
  onToggleSheetHidden: (sheetId: string) => void;
  /** Lets the app-level OS drag-drop route dropped images to the rect under
   *  the cursor. Pass null on unmount. Returns true when a rect took the drop. */
  registerDropHandler: (fn: ((paths: string[], cssX: number, cssY: number) => boolean) | null) => void;
}) {
  const { push } = useToast();
  const [category, setCategory] = useState<string | null>(null);
  const [sheet, setSheet] = useState<ManifestSheet | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  // Zoom/pan state for the sheet view (reset when the sheet changes).
  const [view, setView] = useState({ zoom: 1, x: 0, y: 0 });
  const [sheetImg, setSheetImg] = useState<{ src: string; path: string; forSheet: string } | null>(
    null,
  );
  const [sheetErr, setSheetErr] = useState<string | null>(null);
  const [editMode, setEditMode] = useState(false);
  const [downloading, setDownloading] = useState(false);
  // Rect being live-dragged (rendered instead of the committed rect).
  const [live, setLive] = useState<{ id: string; rect: Rect } | null>(null);
  const liveRef = useRef<{ id: string; rect: Rect } | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const wrapperRef = useRef<HTMLDivElement | null>(null);
  const panRef = useRef<{ startX: number; startY: number; origX: number; origY: number } | null>(
    null,
  );
  const dragRef = useRef<{
    id: string;
    mode: DragMode;
    startX: number;
    startY: number;
    orig: Rect;
  } | null>(null);
  const sheetRef = useRef<ManifestSheet | null>(null);
  sheetRef.current = sheet;
  const editModeRef = useRef(editMode);
  editModeRef.current = editMode;

  const byId = useMemo(() => new Map(overrides.map((o) => [o.id, o])), [overrides]);
  const hiddenSet = useMemo(() => new Set(hidden), [hidden]);
  const hiddenSheetSet = useMemo(() => new Set(hiddenSheets), [hiddenSheets]);

  /** Sheets to show for a category, honoring the unused filter. */
  function visibleSheets(cat: string): ManifestSheet[] {
    return SHEETS.filter(
      (s) => s.category === cat && (showUnused || !hiddenSheetSet.has(s.id)),
    );
  }

  /** Manifest regions + the user's own drawn regions, as one list. Custom
   *  regions carry alphaCoverage 0 so the compile always un-clips their trans
   *  rect (harmless where the mask is already opaque). */
  function sheetPosters(sh: ManifestSheet): ManifestPoster[] {
    const extra = (customRegions[sh.id] ?? []).map((r) => ({
      id: r.id,
      x: r.x,
      y: r.y,
      w: r.w,
      h: r.h,
      alphaCoverage: 0,
    }));
    return [...sh.posters, ...extra];
  }

  function isCustom(sh: ManifestSheet, posterId: string): boolean {
    return (customRegions[sh.id] ?? []).some((r) => r.id === posterId);
  }

  /** Effective rect: custom regions carry their own rect; manifest regions get
   *  the user correction over the generated one. */
  function eff(sh: ManifestSheet, p: ManifestPoster): Rect {
    const custom = (customRegions[sh.id] ?? []).find((r) => r.id === p.id);
    if (custom) return { x: custom.x, y: custom.y, w: custom.w, h: custom.h };
    return rectEdits[`${sh.id}::${p.id}`] ?? { x: p.x, y: p.y, w: p.w, h: p.h };
  }

  function addCustomRegion(sh: ManifestSheet) {
    const el = containerRef.current;
    const rect = el?.getBoundingClientRect();
    // Land the new region in the middle of what's currently on screen.
    const scaleBase = rect ? sh.width / rect.width : 1;
    const cx = rect ? ((rect.width / 2 - view.x) / view.zoom) * scaleBase : sh.width / 2;
    const cy = rect ? ((rect.height / 2 - view.y) / view.zoom) * scaleBase : sh.height / 2;
    const size = Math.round(Math.min(sh.width, sh.height) / (4 * view.zoom));
    const region = {
      id: `custom_${Date.now().toString(36)}`,
      x: Math.round(Math.min(Math.max(0, cx - size / 2), sh.width - size)),
      y: Math.round(Math.min(Math.max(0, cy - size / 2), sh.height - size)),
      w: size,
      h: size,
    };
    onCustomChange(sh.id, [...(customRegions[sh.id] ?? []), region]);
    setSelected(`${sh.id}::${region.id}`);
    push("info", "Region added - drag it into place, resize with the handles");
  }

  function removeCustomRegion(sh: ManifestSheet, posterId: string) {
    onCustomChange(
      sh.id,
      (customRegions[sh.id] ?? []).filter((r) => r.id !== posterId),
    );
    const ovId = `${sh.id}::${posterId}`;
    if (byId.has(ovId)) onRemove(ovId);
    setSelected(null);
  }

  // Search across every sheet + region name (respects the unused filter).
  const results = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return [];
    const out: { sheet: ManifestSheet; poster: ManifestPoster | null }[] = [];
    for (const s of SHEETS) {
      if (!showUnused && hiddenSheetSet.has(s.id)) continue;
      if (s.id.toLowerCase().includes(q) || pretty(s.id).toLowerCase().includes(q)) {
        out.push({ sheet: s, poster: null });
      }
      for (const p of s.posters) {
        if (!showUnused && hiddenSet.has(`${s.id}::${p.id}`)) continue;
        if (p.id.toLowerCase().includes(q) || pretty(p.id).toLowerCase().includes(q)) {
          out.push({ sheet: s, poster: p });
        }
      }
      if (out.length >= 40) break;
    }
    return out.slice(0, 40);
  }, [query, showUnused, hiddenSet, hiddenSheetSet]);

  // Load (decompile once + cache) the sheet's color texture for display.
  useEffect(() => {
    if (!sheet) return;
    let cancelled = false;
    setSheetErr(null);
    setSheetImg(null);
    setView({ zoom: 1, x: 0, y: 0 });
    posterSheet(helperPath, pakPath, sheet.materials[0])
      .then((s) => {
        thumbCache.set(sheet.id, s.colorPng);
        if (!cancelled)
          setSheetImg({ src: convertFileSrc(s.colorPng), path: s.colorPng, forSheet: sheet.id });
      })
      .catch((e) => !cancelled && setSheetErr(String(e)));
    return () => {
      cancelled = true;
    };
  }, [sheet, helperPath, pakPath]);

  function assign(sh: ManifestSheet, poster: ManifestPoster, imagePath: string) {
    const id = `${sh.id}::${poster.id}`;
    const r = eff(sh, poster);
    const existing = byId.get(id);
    if (existing) {
      onUpdate(id, { sourceImage: imagePath });
    } else {
      onAdd({
        id,
        sheetId: sh.id,
        materials: sh.materials,
        posterId: poster.id,
        label: `${pretty(sh.id)} · ${pretty(poster.id)}`,
        x: r.x,
        y: r.y,
        w: r.w,
        h: r.h,
        alphaCoverage: poster.alphaCoverage ?? 1,
        sourceImage: imagePath,
        fit: "cover",
        lastCompiledHash: null,
      });
    }
    setSelected(id);
    push("success", `Art set - ${pretty(poster.id)} (${r.w}×${r.h})`);
  }

  async function pickImage(sh: ManifestSheet, poster: ManifestPoster) {
    const picked = await openDialog({ multiple: false, filters: IMAGE_FILTERS });
    if (typeof picked === "string") assign(sh, poster, picked);
  }

  /** Hide a vanilla decal in-game (no art — its trans mask gets blanked).
   *  For tags/graffiti the map stamps over your own replacement. */
  function eraseRegion(sh: ManifestSheet, poster: ManifestPoster) {
    const id = `${sh.id}::${poster.id}`;
    onAdd({
      id,
      sheetId: sh.id,
      materials: sh.materials,
      posterId: poster.id,
      label: `${pretty(sh.id)} · ${pretty(poster.id)} (hidden)`,
      x: eff(sh, poster).x,
      y: eff(sh, poster).y,
      w: eff(sh, poster).w,
      h: eff(sh, poster).h,
      alphaCoverage: poster.alphaCoverage ?? 1,
      sourceImage: "",
      fit: "cover",
      erase: true,
      lastCompiledHash: null,
    });
    setSelected(id);
    push("success", `${pretty(poster.id)} will be invisible in-game after the next compile`);
  }

  /** Full-sheet replacement: same-size art (usually a downloaded + edited
   *  original) stretched over the whole texture. Keeps the vanilla trans mask
   *  so cut-out shapes stay cut out. */
  async function pickWholeSheet(sh: ManifestSheet) {
    const picked = await openDialog({ multiple: false, filters: IMAGE_FILTERS });
    if (typeof picked !== "string") return;
    const id = `${sh.id}::${WHOLE}`;
    if (byId.has(id)) {
      onUpdate(id, { sourceImage: picked });
    } else {
      onAdd({
        id,
        sheetId: sh.id,
        materials: sh.materials,
        posterId: WHOLE,
        label: `${pretty(sh.id)} · whole sheet`,
        x: 0,
        y: 0,
        w: sh.width,
        h: sh.height,
        alphaCoverage: 1,
        sourceImage: picked,
        fit: "stretch",
        lastCompiledHash: null,
      });
    }
    push("success", `Whole sheet replaced - ${pretty(sh.id)}`);
  }

  async function downloadSheet(sh: ManifestSheet) {
    setDownloading(true);
    try {
      const path =
        sheetImg?.forSheet === sh.id
          ? sheetImg.path
          : (await posterSheet(helperPath, pakPath, sh.materials[0])).colorPng;
      const dest = await copyToDownloads(path);
      push("success", `Saved to ${dest}`);
    } catch (e) {
      push("error", `Download failed: ${e}`);
    } finally {
      setDownloading(false);
    }
  }

  // OS-level drops: the app forwards dropped image paths + cursor position.
  useEffect(() => {
    registerDropHandler((paths, cssX, cssY) => {
      const sh = sheetRef.current;
      if (!sh || paths.length === 0 || editModeRef.current) return false;
      const el = document.elementFromPoint(cssX, cssY)?.closest("[data-poster-rect]");
      const pid = el?.getAttribute("data-poster-rect");
      const poster = sheetPosters(sh).find((p) => p.id === pid);
      if (!poster) return false;
      assign(sh, poster, paths[0]);
      return true;
    });
    return () => registerDropHandler(null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [overrides, rectEdits, customRegions]);

  /** CSS px → sheet px scale for the current (zoomed) content. */
  function sheetScale(sh: ManifestSheet): number {
    const el = wrapperRef.current ?? containerRef.current;
    if (!el) return 1;
    return sh.width / el.getBoundingClientRect().width;
  }

  // Wheel-zoom toward the cursor, clamped 1x..8x (1x resets the pan). A NATIVE
  // non-passive listener: React's synthetic onWheel can't preventDefault (the
  // browser registers it passive), so zooming would also scroll the page.
  useEffect(() => {
    const el = containerRef.current;
    if (!el || !sheet) return;
    const handler = (e: WheelEvent) => {
      e.preventDefault();
      const rect = el.getBoundingClientRect();
      const cx = e.clientX - rect.left;
      const cy = e.clientY - rect.top;
      setView((v) => {
        const zoom = Math.min(8, Math.max(1, v.zoom * (e.deltaY < 0 ? 1.2 : 1 / 1.2)));
        if (zoom === 1) return { zoom: 1, x: 0, y: 0 };
        const k = zoom / v.zoom;
        return { zoom, x: cx - (cx - v.x) * k, y: cy - (cy - v.y) * k };
      });
    };
    el.addEventListener("wheel", handler, { passive: false });
    return () => el.removeEventListener("wheel", handler);
  }, [sheet]);

  /** Pan with middle-drag anywhere, or left-drag on the sheet background. */
  function startPan(e: React.PointerEvent) {
    const isBackground = (e.target as HTMLElement).dataset?.sheetBg === "1";
    if (e.button !== 1 && !(e.button === 0 && isBackground)) return;
    e.preventDefault();
    panRef.current = { startX: e.clientX, startY: e.clientY, origX: view.x, origY: view.y };
    function onMove(ev: PointerEvent) {
      const p = panRef.current;
      if (!p) return;
      setView((v) => ({ ...v, x: p.origX + (ev.clientX - p.startX), y: p.origY + (ev.clientY - p.startY) }));
    }
    function onUp() {
      panRef.current = null;
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onUp);
    }
    window.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onUp);
  }

  /** Jump to a region from search: open its sheet and select it. */
  function gotoRegion(sh: ManifestSheet, posterId: string | null) {
    setCategory(sh.category);
    setSheet(sh);
    setSelected(posterId ? `${sh.id}::${posterId}` : null);
    setQuery("");
  }

  function startDrag(e: React.PointerEvent, sh: ManifestSheet, p: ManifestPoster, mode: DragMode) {
    e.preventDefault();
    e.stopPropagation();
    const id = `${sh.id}::${p.id}`;
    setSelected(id);
    const orig = eff(sh, p);
    dragRef.current = { id, mode, startX: e.clientX, startY: e.clientY, orig };
    liveRef.current = { id, rect: orig };
    setLive(liveRef.current);
    const scale = sheetScale(sh);

    function onMove(ev: PointerEvent) {
      const d = dragRef.current;
      if (!d) return;
      const dx = Math.round((ev.clientX - d.startX) * scale);
      const dy = Math.round((ev.clientY - d.startY) * scale);
      let { x, y, w, h } = d.orig;
      const m = d.mode;
      if (m === "move") {
        x += dx;
        y += dy;
      } else {
        if (m.includes("w")) {
          x += dx;
          w -= dx;
        }
        if (m.includes("e")) w += dx;
        if (m.includes("n")) {
          y += dy;
          h -= dy;
        }
        if (m.includes("s")) h += dy;
      }
      // clamp to the sheet, keep a sane minimum size
      w = Math.max(8, w);
      h = Math.max(8, h);
      x = Math.min(Math.max(0, x), sh.width - 8);
      y = Math.min(Math.max(0, y), sh.height - 8);
      w = Math.min(w, sh.width - x);
      h = Math.min(h, sh.height - y);
      liveRef.current = { id: d.id, rect: { x, y, w, h } };
      setLive(liveRef.current);
    }
    function onUp(ev: PointerEvent) {
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onUp);
      const d = dragRef.current;
      dragRef.current = null;
      const cur = liveRef.current;
      liveRef.current = null;
      setLive(null);
      if (!d || !cur || cur.id !== d.id) return;
      const dx = Math.abs(ev.clientX - d.startX);
      const dy = Math.abs(ev.clientY - d.startY);
      if (dx > 2 || dy > 2) commitRect(d.id, cur.rect);
    }
    window.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onUp);
  }

  /** Persist a rect correction (null = reset to manifest) and keep any existing
   *  override's compile rect in sync. Custom regions carry their own rect. */
  function commitRect(id: string, rect: Rect | null) {
    const sh = sheetRef.current;
    const posterId = sh ? id.slice(sh.id.length + 2) : "";
    if (sh && isCustom(sh, posterId)) {
      if (rect) {
        onCustomChange(
          sh.id,
          (customRegions[sh.id] ?? []).map((r) => (r.id === posterId ? { ...r, ...rect } : r)),
        );
        if (byId.has(id)) onUpdate(id, rect);
      }
      return;
    }
    onRectEdit(id, rect);
    if (byId.has(id)) {
      const p = sh ? sheetPosters(sh).find((pp) => `${sh.id}::${pp.id}` === id) : undefined;
      const effective = rect ?? (p ? { x: p.x, y: p.y, w: p.w, h: p.h } : null);
      if (effective) onUpdate(id, effective);
    }
  }

  function patchSelectedRect(patch: Partial<Rect>) {
    if (!sheet || !selected) return;
    const p = sheetPosters(sheet).find((pp) => `${sheet.id}::${pp.id}` === selected);
    if (!p) return;
    commitRect(selected, { ...eff(sheet, p), ...patch });
  }

  // ---- Category grid --------------------------------------------------------
  if (!category) {
    return (
      <div>
        <p className="mb-4 text-sm text-zinc-500">
          Replace any in-world poster, sign, or graffiti with your own image - drop a PNG on a
          highlighted region (or click it) and the compile paints it into the game's texture
          atlas.
          {overrides.length > 0 && (
            <span className="ml-1 text-emerald-400">
              {overrides.length} replacement{overrides.length === 1 ? "" : "s"} queued.
            </span>
          )}
        </p>
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search posters, signs, graffiti… (e.g. cauldron, hex, panda)"
          className="mb-4 w-full max-w-md rounded-lg border border-zinc-800 bg-zinc-900/60 px-3 py-1.5 text-xs text-zinc-200 placeholder:text-zinc-600 focus:border-zinc-600 focus:outline-none"
        />
        {query.trim() ? (
          <div className="flex flex-col gap-1">
            {results.length === 0 && (
              <div className="text-xs text-zinc-600">No matches for "{query.trim()}".</div>
            )}
            {results.map(({ sheet: s, poster: p }) => {
              const id = p ? `${s.id}::${p.id}` : s.id;
              const ov = p ? byId.get(`${s.id}::${p.id}`) : undefined;
              return (
                <button
                  key={id}
                  onClick={() => gotoRegion(s, p?.id ?? null)}
                  className="flex items-center gap-3 rounded-lg border border-zinc-800 bg-zinc-900/40 px-3 py-1.5 text-left transition hover:border-zinc-600 hover:bg-zinc-900"
                >
                  <span className="min-w-0 flex-1">
                    <span className="block truncate text-xs text-zinc-200">
                      {p ? pretty(p.id) : `${pretty(s.id)} (whole sheet)`}
                    </span>
                    <span className="block truncate text-[10px] text-zinc-500">
                      {pretty(s.id)} · {CATEGORIES.find((c) => c.key === s.category)?.label}
                      {p && ` · ${p.w}×${p.h}`}
                    </span>
                  </span>
                  {ov && (
                    <span className="rounded bg-emerald-500/15 px-1.5 text-[10px] font-semibold text-emerald-300">
                      replaced
                    </span>
                  )}
                </button>
              );
            })}
          </div>
        ) : (
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
          {CATEGORIES.map((c) => {
            const sheets = visibleSheets(c.key);
            if (sheets.length === 0) return null;
            const n = overrides.filter((o) => sheets.some((s) => s.id === o.sheetId)).length;
            const regions = sheets.reduce(
              (acc, s) => acc + s.posters.filter((p) => !hiddenSet.has(`${s.id}::${p.id}`)).length,
              0,
            );
            return (
              <button
                key={c.key}
                onClick={() => setCategory(c.key)}
                className="group relative flex flex-col rounded-xl border border-zinc-800 bg-zinc-900/40 p-4 text-left transition hover:border-zinc-600 hover:bg-zinc-900"
              >
                <span className="text-xl">{c.icon}</span>
                <span className="mt-2 text-sm font-semibold text-zinc-100">{c.label}</span>
                <span className="mt-1 text-[11px] text-zinc-500">{c.hint}</span>
                <span className="mt-2 text-[10px] text-zinc-600">
                  {sheets.length} sheets · {regions} regions
                </span>
                {n > 0 && (
                  <span className="absolute right-2 top-2 rounded bg-emerald-500/15 px-1.5 text-[10px] font-semibold text-emerald-300">
                    {n}
                  </span>
                )}
              </button>
            );
          })}
        </div>
        )}
        {overrides.length > 0 && (
          <div className="mt-6">
            <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-zinc-500">
              Your replacements
            </h3>
            <div className="flex flex-col gap-1">
              {overrides.map((o) => (
                <div
                  key={o.id}
                  className="flex items-center gap-3 rounded-lg border border-zinc-800 bg-zinc-900/40 px-3 py-1.5"
                >
                  {o.erase ? (
                    <span className="flex h-8 w-8 items-center justify-center rounded bg-red-500/10 text-sm">
                      ∅
                    </span>
                  ) : (
                    <img
                      src={convertFileSrc(o.sourceImage)}
                      className="h-8 w-8 rounded object-cover"
                      alt=""
                    />
                  )}
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-xs text-zinc-200">{o.label}</div>
                    <div className="truncate text-[10px] text-zinc-500">
                      {o.w}×{o.h} · {o.erase ? "hidden in-game" : o.fit}
                    </div>
                  </div>
                  <button
                    onClick={() => {
                      const sh = SHEETS.find((s) => s.id === o.sheetId);
                      if (sh) {
                        setCategory(sh.category);
                        setSheet(sh);
                        setSelected(o.id);
                      }
                    }}
                    className="rounded px-2 py-0.5 text-[11px] text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200"
                  >
                    View
                  </button>
                  <button
                    onClick={() => onRemove(o.id)}
                    className="rounded px-2 py-0.5 text-[11px] text-red-400/80 hover:bg-red-500/10 hover:text-red-300"
                  >
                    Remove
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    );
  }

  // ---- Sheet grid within a category ----------------------------------------
  if (!sheet) {
    const sheets = visibleSheets(category);
    return (
      <div>
        <button
          onClick={() => setCategory(null)}
          className="mb-3 text-xs text-zinc-500 hover:text-zinc-300"
        >
          ← All categories
        </button>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
          {sheets.map((s) => {
            const n = overrides.filter((o) => o.sheetId === s.id).length;
            const hid = s.posters.filter((p) => hiddenSet.has(`${s.id}::${p.id}`)).length;
            const sheetHidden = hiddenSheetSet.has(s.id);
            return (
              <button
                key={s.id}
                onClick={() => {
                  setSheet(s);
                  setSelected(null);
                }}
                className={`group relative flex flex-col gap-2 rounded-xl border p-2.5 text-left transition ${
                  sheetHidden
                    ? "border-dashed border-amber-500/40 bg-zinc-900/20 hover:border-amber-500/70"
                    : "border-zinc-800 bg-zinc-900/40 hover:border-zinc-500 hover:bg-zinc-900"
                }`}
              >
                <SheetThumb helperPath={helperPath} pakPath={pakPath} sheet={s} dimmed={sheetHidden} />
                <div className="px-0.5 pb-0.5">
                  <span className="block truncate text-xs font-semibold text-zinc-100">
                    {pretty(s.id)}
                  </span>
                  <span className="mt-0.5 block text-[10px] text-zinc-500">
                    {s.posters.length - hid} region{s.posters.length - hid === 1 ? "" : "s"}
                    {!s.curated && " · auto"}
                    {hid > 0 && ` · ${hid} unused`}
                  </span>
                </div>
                {sheetHidden && (
                  <span className="absolute left-4 top-4 rounded bg-amber-400/90 px-1.5 text-[10px] font-bold text-zinc-900">
                    unused
                  </span>
                )}
                {n > 0 && (
                  <span className="absolute right-4 top-4 rounded bg-emerald-500/90 px-1.5 text-[10px] font-bold text-zinc-900">
                    {n}
                  </span>
                )}
              </button>
            );
          })}
        </div>
      </div>
    );
  }

  // ---- Sheet detail: image + clickable rect overlays ------------------------
  const allPosters = sheetPosters(sheet);
  const selectedDef = selected
    ? allPosters.find((p) => `${sheet.id}::${p.id}` === selected)
    : undefined;
  const selectedIsCustom = selectedDef ? isCustom(sheet, selectedDef.id) : false;
  const selectedOv = selected ? byId.get(selected) : undefined;
  const selectedRect = selectedDef ? eff(sheet, selectedDef) : undefined;
  const selectedEdited = selected ? !!rectEdits[selected] : false;
  const selectedHidden = selected ? hiddenSet.has(selected) : false;
  const wholeOv = byId.get(`${sheet.id}::${WHOLE}`);
  const sheetOverrideCount = overrides.filter((o) => o.sheetId === sheet.id).length;

  const handleCursor: Record<DragMode, string> = {
    move: "move",
    n: "ns-resize",
    s: "ns-resize",
    e: "ew-resize",
    w: "ew-resize",
    nw: "nwse-resize",
    se: "nwse-resize",
    ne: "nesw-resize",
    sw: "nesw-resize",
  };

  return (
    <div>
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <button
          onClick={() => {
            setSheet(null);
            setSelected(null);
            setEditMode(false);
          }}
          className="text-xs text-zinc-500 hover:text-zinc-300"
        >
          ← {CATEGORIES.find((c) => c.key === category)?.label ?? category}
        </button>
        <span className="text-xs text-zinc-600">/</span>
        <span className="text-xs font-semibold text-zinc-200">{pretty(sheet.id)}</span>
        <span className="text-[10px] text-zinc-600">
          {sheet.width}×{sheet.height}
          {!sheet.curated && " · auto-mapped regions"}
        </span>
        {hiddenSheetSet.has(sheet.id) && (
          <span className="rounded bg-amber-400/90 px-1.5 text-[10px] font-bold text-zinc-900">
            unused sheet
          </span>
        )}
        <div className="flex-1" />
        <button
          onClick={() => void downloadSheet(sheet)}
          disabled={downloading}
          className="rounded-lg bg-zinc-800 px-2.5 py-1 text-[11px] font-semibold text-zinc-300 transition hover:bg-zinc-700 disabled:opacity-50"
          title="Save the original sheet texture (PNG) to Downloads - edit it, then use Replace whole sheet"
        >
          {downloading ? "Saving…" : "⬇ Download sheet"}
        </button>
        {!editMode && !wholeOv && (
          <button
            onClick={() => void pickWholeSheet(sheet)}
            className="rounded-lg bg-zinc-800 px-2.5 py-1 text-[11px] font-semibold text-zinc-300 transition hover:bg-zinc-700"
            title="Replace the entire sheet texture with a same-size image (e.g. the downloaded original after editing)"
          >
            Replace whole sheet…
          </button>
        )}
        {editMode && (
          <button
            onClick={() => addCustomRegion(sheet)}
            className="rounded-lg bg-zinc-800 px-2.5 py-1 text-[11px] font-semibold text-zinc-300 transition hover:bg-zinc-700"
            title="Draw a new region for art the generated map doesn't split out"
          >
            ＋ Add region
          </button>
        )}
        {editMode && (
          <button
            onClick={() => onToggleSheetHidden(sheet.id)}
            className="rounded-lg bg-zinc-800 px-2.5 py-1 text-[11px] font-semibold text-zinc-300 transition hover:bg-zinc-700"
            title="Mark every asset on this sheet as unused (e.g. Neon Prime-era leftovers). Hidden unless 'Show unused poster assets' is on in Settings."
          >
            {hiddenSheetSet.has(sheet.id) ? "Mark sheet as used" : "Mark sheet unused"}
          </button>
        )}
        <button
          onClick={() => setEditMode((v) => !v)}
          className={`rounded-lg px-2.5 py-1 text-[11px] font-semibold transition ${
            editMode
              ? "bg-amber-400 text-zinc-900"
              : "bg-zinc-800 text-zinc-300 hover:bg-zinc-700"
          }`}
          title="Adjust region boundaries or mark regions as unused"
        >
          {editMode ? "Done editing" : "Edit regions"}
        </button>
      </div>
      {wholeOv && (
        <div className="mb-3 flex items-center gap-3 rounded-lg border border-emerald-500/30 bg-emerald-500/5 px-3 py-2">
          <img
            src={convertFileSrc(wholeOv.sourceImage)}
            className="h-9 w-9 rounded object-cover"
            alt=""
          />
          <div className="min-w-0 flex-1">
            <div className="text-xs font-semibold text-emerald-300">Whole sheet replaced</div>
            <div className="truncate text-[10px] text-zinc-500">
              Your image compiles over the entire texture; the vanilla cut-out shapes are kept.
            </div>
          </div>
          <button
            onClick={() => void pickWholeSheet(sheet)}
            className="rounded px-2 py-0.5 text-[11px] text-zinc-300 hover:bg-zinc-800"
          >
            Change image…
          </button>
          <button
            onClick={() => onRemove(wholeOv.id)}
            className="rounded px-2 py-0.5 text-[11px] text-red-400/80 hover:bg-red-500/10 hover:text-red-300"
          >
            Remove
          </button>
        </div>
      )}
      <p className="mb-3 text-xs text-zinc-500">
        {editMode
          ? "Drag a region to move it, drag its handles to resize. Mark atlas junk as unused to hide it."
          : "Drop an image onto a region (or click one) to replace that art in-game."}
      </p>
      {sheetErr && (
        <div className="mb-3 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-300">
          Couldn't load the sheet texture: {sheetErr}
        </div>
      )}
      <div className="flex flex-col gap-4 xl:flex-row">
        <div
          ref={containerRef}
          onPointerDown={startPan}
          className="relative w-full max-w-3xl shrink-0 select-none overflow-hidden rounded-lg border border-zinc-800 bg-zinc-950"
          style={{ aspectRatio: `${sheet.width} / ${sheet.height}` }}
        >
          <div
            ref={wrapperRef}
            className="absolute inset-0"
            style={{
              transform: `translate(${view.x}px, ${view.y}px) scale(${view.zoom})`,
              transformOrigin: "0 0",
            }}
          >
          {sheetImg?.forSheet === sheet.id ? (
            <img
              src={sheetImg.src}
              data-sheet-bg="1"
              className="absolute inset-0 h-full w-full"
              alt=""
              draggable={false}
              style={{ cursor: view.zoom > 1 ? "grab" : undefined }}
            />
          ) : (
            !sheetErr && (
              <div className="absolute inset-0 flex items-center justify-center text-xs text-zinc-600">
                Decoding sheet texture…
              </div>
            )
          )}
          {wholeOv && (
            <img
              src={convertFileSrc(wholeOv.sourceImage)}
              data-sheet-bg="1"
              className="absolute inset-0 h-full w-full"
              style={{ objectFit: "fill", opacity: 0.9, cursor: view.zoom > 1 ? "grab" : undefined }}
              alt=""
              draggable={false}
            />
          )}
          {allPosters.map((p) => {
            const id = `${sheet.id}::${p.id}`;
            const isHidden = hiddenSet.has(id);
            if (isHidden && !showUnused) return null;
            const ov = byId.get(id);
            const isSel = selected === id;
            const custom = isCustom(sheet, p.id);
            const r = live?.id === id ? live.rect : eff(sheet, p);
            const pct = {
              left: `${(r.x / sheet.width) * 100}%`,
              top: `${(r.y / sheet.height) * 100}%`,
              width: `${(r.w / sheet.width) * 100}%`,
              height: `${(r.h / sheet.height) * 100}%`,
            };
            return (
              <div
                key={p.id}
                data-poster-rect={p.id}
                title={`${pretty(p.id)} - ${r.w}×${r.h}`}
                onPointerDown={(e) => {
                  if (editMode) startDrag(e, sheet, p, "move");
                }}
                onClick={() => {
                  if (editMode) {
                    setSelected(id);
                  } else {
                    setSelected(id);
                    if (!ov) void pickImage(sheet, p);
                  }
                }}
                className="group absolute overflow-visible transition-colors"
                style={{
                  ...pct,
                  cursor: editMode ? "move" : "pointer",
                  opacity: isHidden ? 0.45 : 1,
                  // border widths counter-scale so zoomed-in editing stays precise
                  border: isHidden
                    ? `${2 / view.zoom}px dashed #f59e0b`
                    : ov?.erase
                      ? `${2 / view.zoom}px dashed #f87171`
                      : ov
                        ? `${2 / view.zoom}px solid #34d399`
                        : custom
                          ? `${2 / view.zoom}px dashed #38bdf8`
                          : isSel
                            ? `${2 / view.zoom}px solid ${accent}`
                            : `${1 / view.zoom}px solid rgba(255,255,255,0.3)`,
                  boxShadow: isSel ? `0 0 0 ${2 / view.zoom}px ${accent}55` : undefined,
                }}
              >
                {/* hover tint + name chip */}
                <div
                  className="pointer-events-none absolute inset-0 opacity-0 transition-opacity group-hover:opacity-100"
                  style={{ background: `${accent}1f` }}
                />
                <span className="pointer-events-none absolute bottom-0 left-0 max-w-full truncate rounded-tr bg-zinc-950/80 px-1 py-0.5 text-[9px] text-zinc-200 opacity-0 transition-opacity group-hover:opacity-100">
                  {pretty(p.id)}
                </span>
                {ov && !isHidden && ov.erase && (
                  <>
                    {/* Erased decal: fully transparent in-game. */}
                    <div className="absolute inset-0" style={{ ...CHECKER, opacity: 0.85 }} />
                    <span className="absolute left-0 top-0 bg-red-400/90 px-1 text-[9px] font-bold text-zinc-900">
                      hidden in-game
                    </span>
                  </>
                )}
                {ov && !isHidden && !ov.erase && (
                  <>
                    {/* Shape-cut regions compile with the rect blanked (the
                        art's alpha becomes the decal shape) - checkerboard
                        behind the preview = "transparent in-game here". */}
                    {(p.alphaCoverage ?? 1) < 0.98 && (
                      <div className="absolute inset-0" style={CHECKER} />
                    )}
                    <img
                      src={convertFileSrc(ov.sourceImage)}
                      style={artStyle(ov, r)}
                      alt=""
                      draggable={false}
                    />
                  </>
                )}
                {isHidden && (
                  <span className="absolute left-0 top-0 bg-amber-400/90 px-1 text-[9px] font-bold text-zinc-900">
                    unused
                  </span>
                )}
                {editMode &&
                  isSel &&
                  (["nw", "n", "ne", "e", "se", "s", "sw", "w"] as DragMode[]).map((m) => {
                    const hs = 10 / view.zoom; // handle size counter-scales with zoom
                    const pos: React.CSSProperties = { width: hs, height: hs };
                    if (m.includes("n")) pos.top = -hs / 2;
                    else if (m.includes("s")) pos.bottom = -hs / 2;
                    else pos.top = `calc(50% - ${hs / 2}px)`;
                    if (m.includes("w")) pos.left = -hs / 2;
                    else if (m.includes("e")) pos.right = -hs / 2;
                    else pos.left = `calc(50% - ${hs / 2}px)`;
                    return (
                      <div
                        key={m}
                        onPointerDown={(e) => startDrag(e, sheet, p, m)}
                        className="absolute z-10 rounded-sm border border-zinc-900"
                        style={{ ...pos, background: accent, cursor: handleCursor[m] }}
                      />
                    );
                  })}
              </div>
            );
          })}
          </div>
          {view.zoom > 1 && (
            <button
              onClick={() => setView({ zoom: 1, x: 0, y: 0 })}
              className="absolute bottom-2 right-2 z-20 rounded-lg bg-zinc-900/90 px-2 py-1 text-[10px] font-semibold text-zinc-300 hover:bg-zinc-800"
            >
              {view.zoom.toFixed(1)}× - Reset view
            </button>
          )}
          <span className="pointer-events-none absolute bottom-2 left-2 z-20 rounded bg-zinc-950/70 px-1.5 py-0.5 text-[9px] text-zinc-500">
            scroll to zoom · drag background to pan
          </span>
        </div>
        <div className="min-w-0 flex-1">
          {selectedDef && selectedRect ? (
            <div className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-4">
              <div className="mb-1 flex items-center gap-2 text-sm font-semibold text-zinc-100">
                {pretty(selectedDef.id)}
                {selectedIsCustom && (
                  <span className="rounded bg-sky-500/15 px-1.5 text-[10px] font-semibold text-sky-300">
                    your region
                  </span>
                )}
                {selectedEdited && (
                  <span className="rounded bg-amber-500/15 px-1.5 text-[10px] font-semibold text-amber-300">
                    adjusted
                  </span>
                )}
                {selectedHidden && (
                  <span className="rounded bg-amber-400/90 px-1.5 text-[10px] font-bold text-zinc-900">
                    unused
                  </span>
                )}
              </div>
              <div className="mb-3 text-[11px] text-zinc-500">
                {selectedRect.w}×{selectedRect.h} at ({selectedRect.x},{selectedRect.y})
                {(selectedDef.alphaCoverage ?? 1) < 0.98 && (
                  <span className="ml-1 text-amber-400">
                    · shape-cut in vanilla - a PNG with transparency keeps its shape in-game;
                    opaque art fills the whole rectangle
                  </span>
                )}
              </div>
              {editMode ? (
                <>
                  <div className="mb-3 grid grid-cols-4 gap-2">
                    {(["x", "y", "w", "h"] as const).map((k) => (
                      <label key={k} className="flex flex-col gap-1 text-[10px] text-zinc-500">
                        {k.toUpperCase()}
                        <input
                          type="number"
                          value={selectedRect[k]}
                          onChange={(e) => {
                            const v = parseInt(e.target.value, 10);
                            if (!Number.isNaN(v)) patchSelectedRect({ [k]: v });
                          }}
                          className="w-full rounded border border-zinc-700 bg-zinc-950 px-1.5 py-1 text-xs text-zinc-200"
                        />
                      </label>
                    ))}
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {selectedIsCustom ? (
                      <button
                        onClick={() => removeCustomRegion(sheet, selectedDef.id)}
                        className="rounded-lg px-3 py-1.5 text-xs font-semibold text-red-400/90 hover:bg-red-500/10 hover:text-red-300"
                      >
                        Delete region
                      </button>
                    ) : (
                      <>
                        <button
                          onClick={() => onToggleHidden(selected!)}
                          className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${
                            selectedHidden
                              ? "bg-zinc-800 text-zinc-200 hover:bg-zinc-700"
                              : "bg-amber-400 text-zinc-900 hover:bg-amber-300"
                          }`}
                        >
                          {selectedHidden ? "Mark as used" : "Mark unused"}
                        </button>
                        {selectedEdited && (
                          <button
                            onClick={() => commitRect(selected!, null)}
                            className="rounded-lg bg-zinc-800 px-3 py-1.5 text-xs text-zinc-200 hover:bg-zinc-700"
                          >
                            Reset to detected
                          </button>
                        )}
                      </>
                    )}
                  </div>
                </>
              ) : selectedOv?.erase ? (
                <>
                  <p className="mb-3 text-xs text-zinc-400">
                    <span className="mr-1 rounded bg-red-400/90 px-1.5 text-[10px] font-bold text-zinc-900">
                      hidden in-game
                    </span>
                    This decal compiles fully transparent - it won't render on any wall.
                  </p>
                  <button
                    onClick={() => onRemove(selectedOv.id)}
                    className="rounded-lg bg-zinc-800 px-3 py-1.5 text-xs text-zinc-200 hover:bg-zinc-700"
                  >
                    Unhide (restore original)
                  </button>
                </>
              ) : selectedOv ? (
                <>
                  <img
                    src={convertFileSrc(selectedOv.sourceImage)}
                    className="mb-3 max-h-40 rounded-lg border border-zinc-800 object-contain"
                    style={CHECKER}
                    alt=""
                  />
                  <div className="mb-3 flex flex-wrap items-center gap-2">
                    <span className="text-[11px] text-zinc-500">Fill mode</span>
                    {(["cover", "contain", "stretch"] as const).map((f) => (
                      <button
                        key={f}
                        onClick={() => onUpdate(selectedOv.id, { fit: f })}
                        className={`rounded px-2 py-0.5 text-[11px] ${
                          selectedOv.fit === f
                            ? "bg-zinc-100 font-semibold text-zinc-900"
                            : "bg-zinc-800 text-zinc-400 hover:text-zinc-200"
                        }`}
                      >
                        {f}
                      </button>
                    ))}
                    <button
                      onClick={() =>
                        onUpdate(selectedOv.id, {
                          rotation: ((selectedOv.rotation ?? 0) + 90) % 360,
                        })
                      }
                      className="rounded bg-zinc-800 px-2 py-0.5 text-[11px] text-zinc-300 hover:text-zinc-100"
                      title="Rotate the art 90° clockwise (some atlas posters are stored sideways)"
                    >
                      ⟳ {selectedOv.rotation ?? 0}°
                    </button>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => void pickImage(sheet, selectedDef)}
                      className="rounded-lg bg-zinc-800 px-3 py-1.5 text-xs text-zinc-200 hover:bg-zinc-700"
                    >
                      Replace image…
                    </button>
                    <button
                      onClick={() => onRemove(selectedOv.id)}
                      className="rounded-lg px-3 py-1.5 text-xs text-red-400/80 hover:bg-red-500/10 hover:text-red-300"
                    >
                      Remove
                    </button>
                  </div>
                </>
              ) : (
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => void pickImage(sheet, selectedDef)}
                    className="rounded-lg px-3 py-1.5 text-xs font-semibold text-zinc-900"
                    style={{ background: accent }}
                  >
                    Choose image…
                  </button>
                  <button
                    onClick={() => eraseRegion(sheet, selectedDef)}
                    className="rounded-lg px-3 py-1.5 text-xs text-red-400/90 hover:bg-red-500/10 hover:text-red-300"
                    title="Compile this decal fully transparent so it disappears from every wall (useful for vanilla tags stamped over your own art)"
                  >
                    Hide in-game
                  </button>
                </div>
              )}
            </div>
          ) : (
            <div className="rounded-xl border border-dashed border-zinc-800 p-4 text-xs text-zinc-600">
              {editMode
                ? "Click a region to adjust its boundaries or mark it unused."
                : "Click a region on the sheet to replace it. Regions outlined green already have your art."}
            </div>
          )}
          {sheetOverrideCount > 0 && (
            <div className="mt-3 text-[11px] text-zinc-500">
              {sheetOverrideCount} replacement{sheetOverrideCount === 1 ? "" : "s"} on this sheet -
              all compile together.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
