// Curated layer: editor names + descriptions for particle classes (C),
// common fields (F), attribute indices (ATTRS), input types (PF_TYPES).
export const C = {
  CParticleSystemDefinition: [
    "Base Properties",
    "The system definition itself - the left-hand Base Properties panel in the editor. Max particle count, constant lifespan/radius/color, bounding behavior, and which renderer batches it uses all live here.",
  ],
  C_INIT_InitFloat: [
    "Init Float",
    "Sets one float attribute (radius, alpha, lifetime, roll...) on each particle when it spawns. The workhorse initializer - pick the attribute in Output Field, feed it a literal, random range, or curve.",
  ],
  C_OP_Decay: [
    "Lifespan Decay",
    "Kills each particle when its age passes its life duration. Nearly every system has one; without it particles live forever.",
  ],
  C_OP_InstantaneousEmitter: [
    "Emit Instantaneously",
    "Emits a burst of particles all at once (num to emit), optionally re-bursting on an interval. Use for explosions and impacts; Emit Continuously is the streaming version.",
  ],
  C_OP_BasicMovement: [
    "Movement Basic",
    "The physics step: applies gravity, drag, and accumulated forces each frame. Without one, velocity and forces do nothing.",
  ],
  C_INIT_CreateWithinSphereTransform: [
    "Position Within Sphere Random",
    "Spawns each particle at a random point in a sphere/shell around a control point, with optional outward speed (speed min/max push particles away from the center).",
  ],
  C_OP_SetFloat: [
    "Set Float",
    "Continuously writes a float attribute every frame (vs Init Float's once-at-spawn). With a curve input this is the generic 'animate anything over life' operator; a Lerp value blends it in softly.",
  ],
  C_OP_RenderSprites: [
    "Render Sprites",
    "The standard camera-facing billboard renderer - almost every visible effect ends in one. Texture, blend mode (Mix Blend Mode), orientation, and sheet-sequence animation controls live here.",
  ],
  C_OP_PositionLock: [
    "Movement Lock to Control Point",
    "Glues particles to a control point so they follow it as it moves (a trail on a moving hero). Start/end fade times let particles gradually break off.",
  ],
  C_OP_InterpolateRadius: [
    "Radius Scale",
    "Scales each particle's radius between a start and end multiplier over a time window of its life. The standard grow/shrink control.",
  ],
  C_INIT_PositionOffset: [
    "Position Modify Offset Random",
    "Nudges each new particle by a random offset between two vectors - turns a point spawn into a small cloud.",
  ],
  C_INIT_RandomColor: [
    "Color Random",
    "Gives each particle a random color between Color1 and Color2 at spawn (plus optional darkening based on distance to a control point). Set both the same to just tint.",
  ],
  C_OP_FadeOutSimple: [
    "Alpha Fade Out Simple",
    "Fades alpha to zero over the last fraction of each particle's life (proportional fade time, measured from the end). The one-knob fade-out.",
  ],
  C_OP_ContinuousEmitter: [
    "Emit Continuously",
    "Streams particles at an emission rate, optionally only for a duration or after a start time. The other half of nearly every effect (vs the burst emitter).",
  ],
  C_OP_ColorInterpolate: [
    "Color Fade",
    "Blends each particle's color to a target color across a window of its life (fade start/end are 0-1 of lifetime). One target only - chaining several does NOT make multi-stop gradients (each lerps initial-to-target every frame, so the last one wins). For rainbows use Set Vector with a gradient input instead.",
  ],
  C_INIT_RandomSequence: [
    "Sequence Random",
    "Picks which animation sequence (row of the sprite sheet) each particle uses - random between min/max, or shuffled to avoid repeats.",
  ],
  C_OP_RenderRopes: [
    "Render Ropes",
    "Draws all particles in the system as one connected tube/beam, in particle-ID order. Beams, cables, lightning, trails-as-geometry. Texture scrolls via UV controls.",
  ],
  C_OP_FadeInSimple: [
    "Alpha Fade In Simple",
    "Fades alpha up from zero over the first fraction of each particle's life. Pairs with Alpha Fade Out Simple.",
  ],
  C_OP_RampScalarLinearSimple: [
    "Ramp Scalar Linear Simple",
    "Adds a constant rate of change to a scalar attribute (e.g. +50 radius per second) during a time window. Simpler cousin of Set Float with a curve.",
  ],
  C_INIT_RingWave: [
    "Position Along Ring",
    "Spawns particles arranged around a ring/circle (even or random spacing), with optional initial speed outward along the ring plane. Shockwaves and ground rings.",
  ],
  C_OP_SpinUpdate: [
    "Rotation Basic",
    "Applies each particle's roll speed to its roll every frame - makes the roll-speed attribute actually spin the sprite.",
  ],
  C_INIT_RandomYawFlip: [
    "Rotation Yaw Flip Random",
    "Randomly mirrors a percentage of particles (flips yaw 180) so a directional texture doesn't visibly repeat.",
  ],
  C_OP_SetVec: [
    "Set Vector",
    "Continuously writes a vector attribute (color, position, normal...) each frame; the vector twin of Set Float. A curve or noise input animates it. With the FLOAT_INTERP_GRADIENT input type this is THE multi-stop color tool: a float (particle age, noise, particle number, rope position) picks a color from a gradient - how vanilla rainbows are authored.",
  ],
  C_INIT_InitialVelocityNoise: [
    "Velocity Noise",
    "Gives each particle a spawn velocity from a noise field - organic, swirling launch directions instead of uniform spread.",
  ],
  C_OP_EndCapTimedDecay: [
    "Lifespan Endcap Timed Decay",
    "When the system is stopped (endcap), kills remaining particles after N seconds so the effect winds down instead of snapping off.",
  ],
  C_OP_RenderTrails: [
    "Render Trails",
    "Stretches each particle into a motion-blur streak between its current and previous position. Length scales with speed (head/tail scale knobs).",
  ],
  C_OP_LerpEndCapScalar: [
    "Lerp EndCap Scalar",
    "When the system is stopped, blends a scalar attribute toward a target value over N seconds (e.g. shrink radius to 0 on shutdown).",
  ],
  C_OP_SetSingleControlPointPosition: [
    "Set Single Control Point Position",
    "Pre-emission: places one control point at a fixed or computed position once (or every frame with 'set once' off). How preview offsets and fake attachment points get set up.",
  ],
  C_OP_RenderModels: [
    "Render Models",
    "Renders a full 3D model at each particle (position, scale from radius, orientation from rotation attributes). Debris chunks, projectiles, skinned copies.",
  ],
  C_INIT_CreateSequentialPathV2: [
    "Position Along Path Sequential",
    "Spawns particles evenly spaced along a path between control points, in order - each new particle takes the next step along the path. Beams made of sprites, chain links.",
  ],
  C_INIT_CreateOnModel: [
    "Position on Model Random",
    "Spawns particles on the model/hitboxes of the entity at a control point - random hitbox points, so the effect covers the character's actual body.",
  ],
  C_INIT_InitVec: [
    "Init Vector",
    "Sets one vector attribute at spawn (the vector twin of Init Float) - commonly used to set color from a control point or a literal.",
  ],
  C_OP_VectorNoise: ["Noise Vector", "Adds animated noise to a vector attribute each frame - wobbly positions, shimmering colors."],
  C_OP_LockToBone: [
    "Movement Lock to Bone",
    "Locks particles to the bone/hitbox they spawned on, so they ride the animation (fire that sticks to a waving arm).",
  ],
  C_OP_CurlNoiseForce: [
    "Curl Noise Force",
    "Pushes particles through a divergence-free curl-noise field - the classic smoke/ember swirl. Noise scale sets swirl size, strength sets push.",
  ],
  C_OP_RenderStandardLight: [
    "Render Standard Light",
    "Each particle becomes a dynamic light (color from particle color, radius from attribute). Expensive; usually 1-4 particles.",
  ],
  C_OP_RenderProjected: [
    "Render Projected",
    "Projects the texture onto world geometry beneath the particle (decal-style) - ground rings, blob shadows, magic circles on floors.",
  ],
  C_INIT_RemapParticleCountToScalar: [
    "Remap Particle Count to Scalar",
    "Maps each particle's spawn index (0,1,2...) to a value - e.g. every next particle slightly bigger, or hue-shifted by index.",
  ],
  C_INIT_VelocityRandom: [
    "Velocity Random",
    "Classic random spawn velocity: random speed within a cone/range of directions. Simpler than Velocity Noise.",
  ],
  C_OP_RemapVelocityToVector: [
    "Remap Velocity to Vector",
    "Copies each particle's velocity into a vector attribute (usually color or normal) - speed-tinted sparks, motion-aligned normals.",
  ],
  C_INIT_NormalAlignToCP: [
    "Normal Align to Control Point",
    "Points each particle's normal along a control point's axis at spawn - so oriented sprites face the way the effect is aimed.",
  ],
  C_OP_MovementRotateParticleAroundAxis: [
    "Movement Rotate Particle Around Axis",
    "Orbits particles around an axis through a control point at a set rate - vortices, halos, tornado shells.",
  ],
  C_INIT_CreateWithinBox: ["Position Within Box Random", "Spawns particles at random points inside a box volume around a control point."],
  C_OP_FadeOut: [
    "Alpha Fade Out Random",
    "Like Alpha Fade Out Simple but the fade start point is randomized per particle between two proportions - group dissolves look less uniform.",
  ],
  C_OP_NormalLock: ["Normal Lock to Control Point", "Keeps particle normals tracking a control point's orientation as it rotates."],
  C_OP_FadeAndKill: [
    "Alpha Fade and Decay",
    "All-in-one: fade in, hold, fade out, then kill the particle - alpha envelope and lifespan in a single operator.",
  ],
  C_INIT_PositionPlaceOnGround: [
    "Position on Ground",
    "Traces downward from the spawn point and sticks the particle to the ground/world surface it hits (with offset and max trace length).",
  ],
  C_INIT_InheritFromParentParticles: [
    "Position From Parent Particles",
    "Child-system initializer: spawns each particle at (and optionally inheriting velocity from) a particle of the parent system.",
  ],
  C_OP_MaintainSequentialPath: [
    "Movement Maintain Position Along Path",
    "Continuously re-distributes particles along the path between control points as it moves - keeps a beam solid while endpoints travel.",
  ],
  C_OP_ConstrainDistance: [
    "Constrain Distance to Control Point",
    "Hard-clamps particles to stay within (or outside) a distance of a control point - keeps a swarm inside an invisible sphere.",
  ],
  C_OP_AttractToControlPoint: [
    "Pull Towards Control Point",
    "Force that accelerates particles toward (positive) or away from (negative force scale) a control point - implosions, suck-ins, repulsion.",
  ],
  C_OP_RemapTransformOrientationToRotations: [
    "Remap CP Orientation to Rotations",
    "Copies a control point's pitch/yaw/roll into particle rotation attributes each frame - sprites that rotate with the attached object.",
  ],
  C_OP_Spin: ["Rotation Spin Roll", "Adds a constant roll rate (with optional spin-down over life) - simpler than driving roll speed yourself."],
  C_OP_SetChildControlPoints: [
    "Set Child Control Points From Particle Positions",
    "Feeds this system's particle positions into child systems' control points - each parent particle can steer a whole child effect.",
  ],
  C_OP_SetControlPointOrientation: [
    "Set Control Point Orientation",
    "Pre-emission: orients a control point (fixed angles, or copied/offset from another CP) - aims everything that reads that CP.",
  ],
  C_OP_ClampScalar: ["Clamp Scalar", "Clamps a scalar attribute between min and max every frame - a safety rail after noise/ramps."],
  C_INIT_RemapTransformOrientationToRotations: [
    "Remap CP Orientation to Rotations (Init)",
    "Same as the operator but once at spawn - particles take the CP's current angles and keep them.",
  ],
  C_INIT_CreateFromParentParticles: [
    "Position From Parent Particles Random",
    "Spawns at randomly chosen parent particles (vs sequential inheritance) with optional velocity inheritance.",
  ],
  C_OP_DistanceToTransform: [
    "Remap Distance to Transform to Scalar",
    "Each frame, measures each particle's distance to a control point and remaps it into an attribute - e.g. fade things near the center.",
  ],
  C_OP_CalculateVectorAttribute: [
    "Calculate Vector Attribute",
    "Small vector calculator: output = A*inputA + B*inputB + scalar*vec... Combines attributes without a chain of remaps.",
  ],
  C_OP_OscillateVector: ["Oscillate Vector", "Sine-wave wobble on a vector attribute (rate, frequency, per-component masks) - flicker, sway, pulse."],
  C_OP_OscillateScalar: ["Oscillate Scalar", "Sine-wave wobble on a scalar attribute - pulsing alpha, breathing radius."],
  C_OP_RampScalarLinear: ["Ramp Scalar Linear Random", "Like Ramp Scalar Linear Simple but the rate is randomized per particle between two values."],
  C_INIT_PositionWarpScalar: ["Position Warp Scalar", "Scales spawn positions (and optionally speed) by a per-particle random factor - stretches the spawn shape."],
  C_OP_SetPerChildControlPoint: [
    "Set Per Child Control Point From Particle Positions",
    "Maps particle N to child N's control point - each child effect follows exactly one parent particle.",
  ],
  C_OP_SetCPOrientationToPointAtCP: [
    "Set CP Orientation to Point at CP",
    "Aims one control point at another - keeps beams and cones tracking a target.",
  ],
  C_INIT_CreationNoise: ["Position Warp Noise", "Noise-displaces spawn positions - breaks up perfectly regular spawn shapes."],
  C_OP_StopAfterCPDuration: [
    "Stop Effect After Duration",
    "Pre-emission: stops the whole system after N seconds (or a CP-driven duration) - self-terminating effects.",
  ],
  C_OP_Orient2DRelToCP: [
    "Rotation Orient Relative to CP",
    "Sets particle roll from the 2D angle to a control point - radial streaks that point at/away from the center.",
  ],
  C_INIT_DistanceToCPInit: [
    "Remap Initial Distance to CP to Scalar",
    "At spawn, converts distance-from-control-point into an attribute - e.g. particles farther out start bigger.",
  ],
  C_OP_SetControlPointToVectorExpression: [
    "Set Control Point to Vector Expression",
    "Pre-emission vector math on control points (CP2 = CP0 + CP1, etc.) - computes helper points other functions read.",
  ],
  C_INIT_NormalOffset: ["Normal Offset", "Adds a (random) offset to particle normals at spawn - scatters the facing of oriented sprites."],
  C_OP_ConstrainDistanceToPath: [
    "Constrain Distance to Path",
    "Keeps particles within a radius of the path between control points - a fat beam volume particles can't leave.",
  ],
  C_OP_MovementPlaceOnGround: [
    "Movement Place on Ground",
    "Continuously traces down and sticks particles to the ground as they move - crawling ground effects that follow terrain.",
  ],
  C_OP_RemapSpeed: ["Remap Speed to Scalar", "Converts each particle's speed into an attribute - fast sparks brighter, slow smoke fatter."],
  C_OP_DampenToCP: ["Movement Dampen Relative to Control Point", "Slows particles as they near a control point - soft arrival instead of overshoot."],
  C_OP_FadeIn: ["Alpha Fade In Random", "Fade-in whose duration is randomized per particle between two proportions."],
  C_OP_NoiseEmitter: ["Emit Noise", "Emission rate driven by a noise function - sputtering, irregular streams."],
  C_OP_WorldTraceConstraint: [
    "Collision via Traces",
    "Real collision: traces particle movement against the world, then slides/bounces/stops (collision mode) with radius scale and bounce/slide knobs. The expensive-but-correct one.",
  ],
  C_OP_InheritFromParentParticlesV2: [
    "Inherit From Parent Particles V2",
    "Continuously copies an attribute from the corresponding parent particle - children that track parent color/alpha live.",
  ],
  C_OP_SetControlPointFieldToScalarExpression: [
    "Set CP Field to Scalar Expression",
    "Pre-emission scalar math written into one component of a control point.",
  ],
  C_OP_OscillateScalarSimple: ["Oscillate Scalar Simple", "One-knob sine oscillation on a scalar attribute (rate, frequency, oscillation multiplier)."],
  C_OP_RemapSpeedtoCP: ["Remap Speed to CP", "Pre-emission: writes a measured speed into a control point field for other systems to read."],
  C_INIT_RandomSecondSequence: ["Second Sequence Random", "Random pick for the second sprite-sheet sequence (used by dual-sequence shaders)."],
  C_OP_SetControlPointPositions: [
    "Set Control Point Positions",
    "Pre-emission: places up to four control points at literal positions in one operator - scene setup for preview and simple effects.",
  ],
  C_OP_SetControlPointRotation: ["Set Control Point Rotation", "Pre-emission: spins a control point around an axis at a rate - rotating emission shapes."],
  C_OP_PinParticleToCP: [
    "Pin Particle to Control Point",
    "Pins one chosen particle (first/last/index) to a control point - anchor the end of a rope while the rest dangles.",
  ],
  C_OP_RemapDirectionToCPToVector: [
    "Remap Direction to CP to Vector",
    "Writes the normalized direction toward a control point into a vector attribute - radial normals, inward color grades.",
  ],
  C_OP_SetFloatCollection: ["Set Float Collection", "Like Set Float but writes a system-wide (collection) float shared by all particles."],
  C_OP_LerpScalar: ["Lerp Initial Scalar", "Blends a scalar attribute from its spawn value toward a target over a time window."],
  C_INIT_InheritVelocity: ["Velocity Inherit from CP", "Particles start with a fraction of the control point's (owner's) velocity - effects thrown off a moving hero."],
  C_INIT_CreateAlongPath: ["Position Along Path Random", "Spawns at random points along the path between control points (vs sequential spacing)."],
  C_OP_RadiusDecay: ["Lifespan Minimum Radius Decay", "Kills particles whose radius drops below a threshold - cleans up shrunk-to-nothing particles."],
  C_INIT_StatusEffectCitadel: ["Init Status Effect (Citadel)", "Deadlock-specific: initializes the status-effect overlay parameters (the hero-tint/overlay system)."],
  C_OP_RenderStatusEffectCitadel: ["Render Status Effect (Citadel)", "Deadlock-specific renderer that applies the status-effect overlay to the target model (ice, fire, curse skins)."],
  C_OP_RandomForce: ["Random Force", "Uniform random jitter force within min/max bounds each frame - cheap brownian shake."],
  C_INIT_InitSkinnedPositionFromCPSnapshot: [
    "Position Skinned From CP Snapshot",
    "Spawns particles at the vertices/bones of a model snapshot stored at a control point - full-body model dissolves.",
  ],
  C_OP_RemapCrossProductOfTwoVectorsToVector: ["Remap Cross Product to Vector", "vecA x vecB into an attribute - perpendicular axes for orbit math."],
  C_OP_HSVShiftToCP: [
    "HSV Shift to Control Point",
    "Pre-emission: hue/sat/value-shifts a color stored in a control point - team-coloring and variant tinting at the CP level.",
  ],
  C_INIT_RemapTransformToVector: ["Remap Transform to Vector (Init)", "Writes a control point's position (optionally offset/random within a range) into a vector attribute at spawn."],
  C_OP_Noise: ["Noise Scalar", "Adds animated scalar noise to an attribute - flickering alpha, jittering radius."],
  C_OP_MaxVelocity: ["Movement Max Velocity", "Caps particle speed - lets forces push hard without particles teleporting."],
  C_INIT_PositionWarp: ["Position Warp Random", "Scales spawn positions/velocities by a random vector between two bounds - squash/stretch of the spawn volume, optionally over time."],
  C_OP_RemapCPtoScalar: ["Remap CP to Scalar", "Reads one component of a control point into a per-particle attribute (with input/output remap ranges)."],
  C_OP_RopeSpringConstraint: ["Rope Spring Constraint", "Spring solver between consecutive particles - makes Render Ropes chains behave like slack/taut rope."],
  C_INIT_SetVectorAttributeToVectorExpression: ["Init Vector From Expression", "Vector math at spawn written into an attribute."],
  C_OP_SetParentControlPointsToChildCP: ["Set Parent CPs to Child CP", "Pre-emission: pushes a child system's control point back up to the parent."],
  C_INIT_Orient2DRelToCP: ["Rotation Orient Relative to CP (Init)", "Sets spawn roll from the 2D angle to a control point."],
  C_OP_TwistAroundAxis: ["Twist Around Axis", "Force that twists particles around an axis - tornado rotation as a force rather than hard orbiting."],
  C_INIT_SequenceLifeTime: ["Lifetime From Sequence", "Sets particle lifetime to exactly one playthrough of its sprite-sheet animation - no cut-off flipbooks."],
  C_OP_SetToCP: ["Movement Set to Control Point", "Teleports particles to the control point position each frame (with offset) - hard-attached single sprites."],
  C_INIT_InitFromCPSnapshot: ["Init From CP Snapshot", "Reads per-particle attributes out of a snapshot stored at a control point."],
  C_OP_RenderCables: ["Render Cables", "Tessellated cable/wire renderer with proper material support - hanging wires, chains."],
  C_OP_RampScalarSpline: ["Ramp Scalar Spline Random", "Curved (spline-eased) ramp of a scalar attribute, randomized per particle."],
  C_OP_SetVectorAttributeToVectorExpression: ["Set Vector From Expression", "Per-frame vector math written into an attribute."],
  C_OP_SnapshotRigidSkinToBones: ["Movement Skin to Bones Rigid", "Rigidly skins snapshot particles to the model's bones so they ride animation."],
  C_OP_SetControlPointsToParticle: ["Set Control Points From Particle Positions", "Writes particle positions back into this system's own control points."],
  C_INIT_AgeNoise: ["Lifetime Pre-Age Noise", "Starts particles pre-aged by a noise amount - staggers flipbooks/fades so they don't sync."],
  C_OP_RenderOmni2Light: ["Render Omni2 Light", "Newer omni light renderer per particle (falloff, cone options) - Deadlock's current dynamic-light path."],
  C_OP_CycleScalar: ["Cycle Scalar", "Loops an attribute through a 0..1 cycle over time - the classic hue-cycling/looping driver."],
  C_INIT_CreateSpiralSphere: ["Position on Spiral Sphere", "Spawns particles in a spiral wrapped around a sphere surface."],
  C_OP_AlphaDecay: ["Lifespan Minimum Alpha Decay", "Kills particles whose alpha drops below a threshold."],
  C_OP_SpinYaw: ["Rotation Spin Yaw", "Constant yaw rotation rate (for oriented/3D-facing sprites)."],
  C_OP_SetAttributeToScalarExpression: ["Set Float From Expression", "Per-frame scalar math (A op B, remapped) written into an attribute."],
  C_OP_RenderDeferredLight: ["Render Deferred Light", "Legacy deferred light renderer per particle."],
  C_OP_PercentageBetweenTransforms: ["Remap % Between Transforms to Scalar", "Where a particle sits between two control points (0..1) into an attribute."],
  C_INIT_CreateInEpitrochoid: ["Position in Epitrochoid", "Spawns along a spirograph curve - fancy magic circles."],
  C_INIT_RemapInitialTransformDirectionToRotation: ["Init Rotation From CP Direction", "Spawn roll/yaw taken from a control point's facing."],
  C_OP_RemapTransformOrientationToYaw: ["Rotation From CP Yaw", "Continuously copies a CP's yaw into particle yaw."],
  C_OP_RenderScreenShake: ["Render Screen Shake", "Not visual: shakes the local player's screen based on particle count/attributes. Amplitude, frequency, duration knobs."],
  C_OP_RenderBlobs: ["Render Blobs", "Metaball renderer - particles merge into a blobby fluid surface (Viscous!)."],
  C_OP_RemapCPtoVector: ["Remap CP to Vector", "Reads a control point's position/value into a vector attribute per frame."],
  C_INIT_VelocityFromCP: ["Velocity Set From Control Point", "Spawn velocity taken from a control point's stored vector (with scale)."],
  C_OP_MaintainEmitter: ["Emit to Maintain Count", "Emits exactly enough to keep N particles alive - constant-density fields regardless of lifetime."],
  C_OP_RemapVisibilityScalar: ["Remap Visibility to Scalar", "Scales an attribute by how visible (on-screen, unoccluded) the effect's CP is - lens flares that dim when blocked."],
  C_OP_RotateVector: ["Rotate Vector", "Rotates a vector attribute around an axis at a rate (optionally normalized) - spinning normals/colors."],
  C_OP_DistanceBetweenCPsToCP: ["Distance Between CPs to CP", "Pre-emission: measures CP-to-CP distance, writes it into a CP field - beams that know their length."],
  C_OP_RepeatedTriggerChildGroup: ["Repeated Trigger Child Group", "Pre-emission: fires a group of child systems on a timer - repeating sub-explosions."],
  C_INIT_VelocityRadialRandom: ["Velocity Radial Random", "Spawn velocity pointing radially away from a control point, random magnitude."],
  C_INIT_CreateSequentialPath: ["Position Along Path Sequential (V1)", "Older sequential-path spawner - V2 replaced it; still in a few legacy effects."],
  C_INIT_RemapScalarToVector: ["Remap Scalar to Vector (Init)", "Spreads a scalar (e.g. spawn index) across a vector range at spawn - index-driven color gradients."],
  C_INIT_InitFromParentKilled: ["Init From Killed Parent", "Spawns when a parent particle dies, inheriting its attributes - death-burst chains (firework trails into pops)."],
  C_OP_OscillateVectorSimple: ["Oscillate Vector Simple", "One-knob sine oscillation on a vector attribute."],
  C_OP_RemapScalar: ["Remap Scalar", "Remaps an attribute from one range to another into an output attribute."],
  C_INIT_RandomNamedModelSequence: ["Random Named Model Sequence", "Random animation sequence pick for model-rendered particles."],
  C_OP_TurbulenceForce: ["Turbulent Force", "Layered turbulence force field (4 frequency/amplitude pairs)."],
  C_OP_OrientTo2dDirection: ["Rotation Orient to 2D Direction", "Rolls sprites to face their movement direction - directional streaks without trails."],
  C_OP_SetControlPointToCenter: ["Set CP to Center", "Pre-emission: centers a control point on the particle bounds (min/max/center)."],
  C_OP_SetControlPointsToModelParticles: ["Set CPs to Model Particles", "Binds child CPs to specific bones/attachments of model particles."],
  C_OP_SetControlPointToPlayer: ["Set CP to Player", "Pre-emission: pins a control point to the local player's position/eyes."],
  C_OP_SetFromCPSnapshot: ["Set From CP Snapshot", "Per-frame attribute read-back from a CP snapshot (animated snapshot playback)."],
  C_OP_FadeAndKillForTracers: ["Alpha Fade and Decay (Tracers)", "Tracer-tuned fade envelope + kill."],
  C_OP_EndCapDecay: ["Lifespan Endcap Decay", "On endcap, switches particles to a (shorter) remaining lifetime."],
  C_OP_SetControlPointToImpactPoint: ["Set CP to Impact Point", "Pre-emission: traces from a CP along a direction and puts a CP at the hit point - ground scorch under an airborne explosion."],
  C_INIT_SetAttributeToScalarExpression: ["Init Float From Expression", "Scalar math at spawn written into an attribute."],
  C_INIT_MoveBetweenPoints: ["Move Between Points", "Particles spawn moving from one CP toward another with speed/arrival controls - homing sparks."],
  C_OP_LerpEndCapVector: ["Lerp EndCap Vector", "On endcap, blends a vector attribute toward a target over time."],
  C_INIT_VelocityFromNormal: ["Velocity From Normal", "Spawn velocity along the particle's normal (times a scale) - surface-bursts that pop outward."],
  C_OP_SetCPOrientationToDirection: ["Set CP Orientation to Direction", "Orients a CP along a direction vector each frame."],
  C_OP_RenderLightBeam: ["Render Light Beam", "Volumetric light-beam renderer."],
  C_OP_DistanceBetweenTransforms: ["Distance Between Transforms to Scalar", "Distance between two CPs into a per-particle attribute."],
  C_INIT_CreatePhyllotaxis: ["Position With Phyllotaxis", "Sunflower-seed spiral distribution - even organic coverage of a disc."],
  C_OP_PlaneCull: ["Cull on Plane Crossing", "Kills particles crossing a plane."],
  C_OP_DistanceCull: ["Cull on Sphere Crossing", "Kills particles crossing a sphere boundary."],
  C_OP_VelocityDecay: ["Lifespan Minimum Velocity Decay", "Kills particles that slow below a speed threshold."],
  C_OP_RemapVectortoCP: ["Remap Vector to CP", "Writes a particle's vector attribute into a control point (chosen particle index)."],
  C_OP_PlanarConstraint: ["Prevent Passing Through Plane", "Cheap collision against one infinite plane (usually the ground)."],
  C_OP_RemapCPtoCP: ["Remap CP to CP", "Pre-emission: copies/remaps one CP field into another."],
  C_OP_LocalAccelerationForce: ["Local Acceleration Force", "Constant acceleration in a CP's local space - directional gravity that rotates with the emitter."],
  C_INIT_InitFloatCollection: ["Init Float Collection", "Sets a system-wide float once at system start."],
  C_OP_RemapTransformToVelocity: ["Remap CP Movement to Velocity", "Converts a control point's movement into particle velocity - particles flung by the emitter's motion."],
  C_INIT_CreateOnGrid: ["Position On Grid", "Spawns particles on a regular grid layout."],
  C_INIT_SetHitboxToClosest: ["Set Hitbox to Closest", "Assigns each particle the nearest hitbox - for hitbox-following operators."],
  C_OP_BoxConstraint: ["Constrain to Box", "Keeps particles inside a box volume."],
  C_OP_RenderScreenVelocityRotate: ["Render Screen Velocity Rotate", "Rotates sprites by their screen-space velocity direction (legacy tracer look)."],
  C_OP_RenderSound: ["Render Sound", "Not visual: plays/positions a sound event from the particle system."],
  C_INIT_InitialRepulsionVelocity: ["Velocity Repulse From World", "Spawn velocity pushing away from nearby world geometry."],
  C_OP_LerpVector: ["Lerp Initial Vector", "Blends a vector attribute from spawn value to a target over a window."],
  C_OP_MoveToHitbox: ["Movement Lerp to Hitbox", "Moves particles onto their assigned model hitbox over time - reverse-dissolve onto a character."],
  C_OP_InheritFromParentParticles: ["Inherit Attribute From Parent (op)", "Per-frame copy of an attribute from parent particles (older version)."],
  C_OP_ColorInterpolateRandom: ["Color Fade Random", "Color fade toward a random target color chosen per particle between two colors."],
  C_OP_SetRandomControlPointPosition: ["Set Random CP Position", "Pre-emission: places a CP at a random point in a box, re-rolling on an interval - wandering emitters."],
  C_OP_ClampVector: ["Clamp Vector", "Per-component clamp of a vector attribute."],
  C_OP_NormalizeVector: ["Normalize Vector", "Normalizes a vector attribute each frame."],
  C_OP_IntraParticleForce: ["Intra-Particle Force", "Particles push/pull each other (attraction/repulsion within the system) - clumping or spreading swarms."],
  C_OP_SetUserEvent: ["Fire User Event", "Fires a game event when conditions hit - hooks particles to gameplay code."],
  C_OP_ConstrainDistanceToUserSpecifiedPath: ["Constrain to User Path", "Keeps particles near a hand-authored point path."],
  C_OP_RestartAfterDuration: ["Restart After Duration", "Restarts the system after N seconds - looping one-shot effects."],
  C_OP_PerParticleForce: ["Per-Particle Force", "Force vector driven per particle from an input (attribute/noise)."],
  C_OP_ExternalWindForce: ["External Wind Force", "Applies the map's wind (plus scale) to particles."],
  C_OP_TimeVaryingForce: ["Time Varying Force", "Force that interpolates between a start and end vector over system time."],
  C_OP_ControlpointLight: ["Color Light From Control Points", "Legacy: tints particles by up to 4 fake lights placed at CPs."],
  C_OP_VelocityMatchingForce: ["Movement Match Velocities", "Boids-style: particles steer toward neighbors' average velocity."],
  C_INIT_SetHitboxToModel: ["Set Hitbox to Model", "Assigns hitbox indices across the whole model for even coverage."],
  C_OP_EnableChildrenFromParentParticleCount: ["Enable Children by Particle Count", "Turns child systems on/off based on how many parent particles exist."],
  C_OP_SelectivelyEnableChildren: ["Selectively Enable Children", "Enables a chosen subset of child systems (by index/CP value) - variant switching inside one effect."],
  C_INIT_QuantizeFloat: ["Quantize Float (Init)", "Snaps an attribute to steps of N at spawn."],
  C_OP_LagCompensation: ["Movement Lag Compensation", "Rewinds CP-attached movement for server lag - netcode-correct tracers."],
  C_OP_ReinitializeScalarEndCap: ["Reinitialize Scalar on EndCap", "On endcap, re-randomizes a scalar attribute."],
  C_OP_ModelCull: ["Cull by Model", "Kills particles inside/outside the model's volume."],
  C_OP_ChooseRandomChildrenInGroup: ["Choose Random Children in Group", "Pre-emission: enables a random child from a group - random variant per play."],
  C_OP_MovementMaintainOffset: ["Movement Maintain Offset", "Keeps particles at their spawn-time offset from a CP."],
  C_OP_CollideWithSelf: ["Collide With Self", "Simple particle-vs-particle collision within the system."],
  C_OP_LerpToInitialPosition: ["Lerp to Initial Position", "Pulls particles back toward where they spawned (relative to a CP) - elastic return."],
  C_OP_DecayOffscreen: ["Lifespan Decay When Offscreen", "Kills particles faster when nobody can see them."],
  C_OP_LightningSnapshotGenerator: ["Lightning Snapshot Generator", "Builds a lightning-bolt point set into a snapshot for a rope renderer to draw."],
  C_OP_ExternalGameImpulseForce: ["External Game Impulse Force", "Reacts to game-generated impulses (explosions pushing smoke)."],
  C_INIT_SequenceFromCP: ["Sequence From CP", "Sprite-sheet sequence index read from a control point."],
  C_OP_SetControlPointToHMD: ["Set CP to HMD", "VR headset position into a CP (unused in Deadlock)."],
  C_OP_ForceControlPointStub: ["Force Control Point Stub", "Marks a CP as externally driven (tool/editor helper)."],
  C_OP_PlayEndCapWhenFinished: ["Play EndCap When Finished", "Triggers the endcap state automatically when emission finishes."],
  C_OP_SetControlPointPositionToRandomActiveCP: ["Set CP to Random Active CP", "Copies a randomly chosen active CP into another CP."],
  C_INIT_RadiusFromCPObject: ["Radius From CP Object", "Spawn radius taken from the size of the object at a CP."],
  C_OP_CPOffsetToPercentageBetweenCPs: ["CP Offset to % Between CPs", "Writes how far a CP sits between two others into a CP field."],
  C_OP_ControlPointToRadialScreenSpace: ["CP to Radial Screen Space", "Projects a CP into radial screen coordinates (HUD-space effects)."],
  C_INIT_RemapInitialDirectionToTransformToVector: ["Init Direction to CP to Vector", "Spawn-time direction toward a CP written into a vector attribute."],
  C_INIT_RemapParticleCountToNamedModelMeshGroupScalar: ["Particle Count to Mesh Group", "Maps spawn index to a model mesh group."],
  C_OP_RemapControlPointOrientationToRotation: ["Remap CP Orientation to Rotation", "One CP axis angle into a rotation attribute."],
  C_OP_RemapDistanceToLineSegmentToScalar: ["Distance to Line Segment to Scalar", "Distance from the CP0-CP1 line into an attribute."],
  C_OP_RemapVectorComponentToScalar: ["Vector Component to Scalar", "Pulls one component (x/y/z) of a vector attribute into a scalar attribute."],
  C_OP_MovementSkinnedPositionFromCPSnapshot: ["Movement Lerp to Skinned Snapshot", "Animates particles toward skinned snapshot positions - model-forming swarms."],
  C_OP_RemapParticleCountOnScalarEndCap: ["Particle Count to Scalar on EndCap", "On endcap, remaps live particle count into an attribute."],
  C_OP_SetFloatAttributeToVectorExpression: ["Set Float From Vector Expression", "Vector math reduced to a scalar, written per frame."],
  C_OP_RampScalarSplineSimple: ["Ramp Scalar Spline Simple", "Simple eased ramp of a scalar attribute."],
  C_OP_SetControlPointOrientationToCPVelocity: ["Set CP Orientation to CP Velocity", "Aims a CP along its own movement direction."],
  C_OP_SetPerChildControlPointFromAttribute: ["Set Per Child CP From Attribute", "Particle N's chosen attribute into child N's control point."],
  C_INIT_CreateOnModelAtHeight: ["Position on Model at Height", "Spawns on the model but only at a given height band."],
  C_INIT_VelocityRepulseFromWorld: ["Velocity Repulse From World", "Spawn velocity away from nearby geometry."],
};

// Descriptions for fields that appear across many classes.
export const F = {
  m_flOpStartFadeInTime: "Start of the window (in each particle's life, seconds or 0-1 of life) where this function's effect ramps IN.",
  m_flOpEndFadeInTime: "End of the ramp-in window - full effect after this.",
  m_flOpStartFadeOutTime: "Start of the window where the effect ramps OUT.",
  m_flOpEndFadeOutTime: "End of the ramp-out window - no effect after this.",
  m_flOpFadeOscillatePeriod: "Repeats the fade in/out envelope on this period - pulsing operators.",
  m_flOpStrength: "Master strength multiplier for this function (an input, so it can be a curve/random).",
  m_nOpEndCapState: "Whether this function runs during the endcap (the effect's stop/wind-down phase): always, disabled during endcap, or ONLY during endcap.",
  m_bDisableOperator: "Function is switched off but kept in the file (the checkbox next to its name in the editor).",
  m_nOpTimeOffsetSeed: "Random seed for per-particle time offsets of this function.",
  m_flOpTimeOffsetSeconds: "Shifts this function's clock by N seconds.",
  m_flOpTimeScaleSeconds: "Rescales this function's clock (2 = runs twice as fast).",
  m_bNormalizeToStopTime: "Measure fade windows against the effect's stop time instead of particle lifetime.",
  m_nFieldOutput: "Which per-particle attribute this writes - see the attribute table above.",
  m_nFieldInput: "Which per-particle attribute this reads.",
  m_nSetMethod: "How the value lands: set it, add to it, scale it, or blend toward it (SET / ADD / SCALE / MULTIPLY...).",
  m_nControlPointNumber: "Which control point (CP) this function is anchored to / reads from.",
  m_nCP: "Which control point this function uses.",
  m_TransformInput: "The transform (control point, named transform, or literal) this function measures against.",
  m_vecOutputMin: "Output range minimum (input range maps onto output range).",
  m_vecOutputMax: "Output range maximum.",
  m_flOutputMin: "Output range minimum.",
  m_flOutputMax: "Output range maximum.",
  m_flInputMin: "Input range minimum before remapping.",
  m_flInputMax: "Input range maximum before remapping.",
  m_bScaleInitialRange: "Multiply the attribute's existing value instead of overwriting it.",
  m_bActiveRange: "Only apply while the input is inside the input range.",
  m_nColorBlendMode: "How this color combines with the particle's current color (replace, multiply, add...).",
  m_ColorFade: "The target color to blend toward.",
  m_flFadeStartTime: "When the blend starts, as 0-1 of the particle's life.",
  m_flFadeEndTime: "When the blend completes, as 0-1 of the particle's life.",
  m_bEaseInOut: "Smooth (eased) blend instead of linear.",
  m_nParticlesToEmit: "How many particles this burst emits (an input - can be random or CP-driven).",
  m_flStartTime: "Delay before this emitter starts, in seconds.",
  m_flEmitRate: "Particles per second (an input - curves make ramping streams).",
  m_flEmissionDuration: "How long the emitter runs; 0 = forever.",
  m_ColorMin: "Random color range: low end.",
  m_ColorMax: "Random color range: high end.",
  m_flRadius: "Spawn distance / sphere radius (an input).",
  m_vecDistanceBias: "Per-axis squash/stretch of the spawn sphere (1,1,0 flattens it to a disc).",
  m_fSpeedMin: "Random outward spawn speed: low end.",
  m_fSpeedMax: "Random outward spawn speed: high end.",
  m_LocalCoordinateSystemSpeedMin: "Extra spawn speed in the CP's local axes (x = along its forward): low end.",
  m_LocalCoordinateSystemSpeedMax: "Extra spawn speed in the CP's local axes: high end.",
  m_nSequenceMin: "Lowest sprite-sheet sequence index to pick from.",
  m_nSequenceMax: "Highest sprite-sheet sequence index to pick from.",
  m_flGravityScale: "How much world gravity applies (1 = full, negative = floats up).",
  m_fDrag: "Air resistance - fraction of velocity removed per frame.",
  m_nMaxParticles: "Hard cap on live particles in this system - memory is reserved for all of them.",
  m_flConstantLifespan: "Default life duration when no initializer sets one.",
  m_flConstantRadius: "Default radius when no initializer sets one.",
  m_ConstantColor: "Default color/alpha when nothing sets one.",
  m_nBehaviorVersion: "Engine compatibility version - leave it alone; changing it changes how old fields are interpreted.",
  m_hTexture: "The texture this renderer draws.",
  m_nOrientationType: "How sprites face: screen-facing, world Z-up, aligned to normal/velocity, etc.",
  m_flRadiusScale: "Extra multiplier on particle radius at render time (an input).",
  m_flAlphaScale: "Extra multiplier on particle alpha at render time (an input).",
  m_vecColorScale: "Render-time color multiplier (an input - useful for team tint).",
  m_nSequenceCombineMode: "How the two sprite-sheet sequences combine in the shader.",
  m_bGammaCorrectVertexColors: "Apply gamma correction to vertex colors (leave as vanilla does).",
  m_flAnimationRate: "Sprite-sheet playback rate (frames scale with this).",
  m_bAnimateInFPS: "Interpret animation rate as frames-per-second instead of cycles-per-life.",
  m_nOutputBlendMode: "Blend mode: additive glows, alpha-blended smoke, multiply shadows.",
};

// The per-particle attribute table (what m_nFieldOutput numbers mean).
export const ATTRS = [
  ["0", "Position", "world position (vector)"],
  ["1", "Life Duration", "how long this particle lives"],
  ["2", "Previous Position", "position last frame (trails read this)"],
  ["3", "Radius", "sprite size"],
  ["4", "Roll", "2D rotation of the sprite"],
  ["5", "Roll Speed", "rotation rate"],
  ["6", "Color", "RGB tint (vector)"],
  ["7", "Alpha", "opacity"],
  ["8", "Creation Time", "when it spawned"],
  ["9", "Sequence Number", "sprite-sheet animation row"],
  ["10", "Trail Length", "streak length for trail renderers"],
  ["11", "Particle ID", "stable index (ropes sort by this)"],
  ["12", "Yaw", "3D yaw for oriented sprites"],
  ["13", "Second Sequence", "second sprite-sheet row (dual-sequence shaders)"],
  ["14", "Hitbox Index", "which model hitbox it belongs to"],
  ["15", "Hitbox Offset", "position relative to that hitbox (vector)"],
  ["16", "Alpha Alternate", "second alpha channel - many shaders multiply both"],
  ["17", "Scratch Vector", "free vector workspace for chaining operators"],
  ["18", "Scratch Float", "free float workspace for chaining operators"],
  ["20", "Pitch", "3D pitch for oriented sprites"],
  ["21", "Normal", "facing direction (vector)"],
  ["22", "Glow RGB", "self-illum color (some shaders)"],
  ["23", "Glow Alpha", "self-illum strength"],
];

// Float/vector input types (the dropdown every "input" field has in the editor).
export const PF_TYPES = [
  ["Literal", "a plain number - the same for every particle"],
  ["Random Uniform / Biased", "rolled per particle between min and max (biased bends the distribution)"],
  ["Particle Age", "a curve evaluated over the particle's life - THE way to animate a property"],
  ["Collection Age", "a curve over the whole system's age"],
  ["Control Point Component", "read live from a control point's position or stored data"],
  ["Particle Attribute", "read another attribute of the same particle (optionally remapped)"],
  ["Named Value", "read a named parameter the game/gameplay code drives"],
  ["Noise", "animated noise field (scale, octaves, turbulence knobs)"],
];
